// 500 parole italiane comuni suddivise per numero di sillabe
// Formato: { parola: "pane", sillabe: ["pa", "ne"] }

const parole = [

  // ── BISILLABE (150 parole) ────────────────────────────────────────────────
  { parola: "pane",    sillabe: ["pa",   "ne"]    },
  { parola: "casa",    sillabe: ["ca",   "sa"]    },
  { parola: "mare",    sillabe: ["ma",   "re"]    },
  { parola: "sole",    sillabe: ["so",   "le"]    },
  { parola: "luna",    sillabe: ["lu",   "na"]    },
  { parola: "fiore",   sillabe: ["fio",  "re"]    },
  { parola: "cielo",   sillabe: ["cie",  "lo"]    },
  { parola: "piede",   sillabe: ["pie",  "de"]    },
  { parola: "mano",    sillabe: ["ma",   "no"]    },
  { parola: "bocca",   sillabe: ["boc",  "ca"]    },
  { parola: "vita",    sillabe: ["vi",   "ta"]    },
  { parola: "tempo",   sillabe: ["tem",  "po"]    },
  { parola: "cane",    sillabe: ["ca",   "ne"]    },
  { parola: "gatto",   sillabe: ["gat",  "to"]    },
  { parola: "pesce",   sillabe: ["pe",   "sce"]   },
  { parola: "latte",   sillabe: ["lat",  "te"]    },
  { parola: "acqua",   sillabe: ["ac",   "qua"]   },
  { parola: "papà",    sillabe: ["pa",   "pà"]    },
  { parola: "mamma",   sillabe: ["mam",  "ma"]    },
  { parola: "gioco",   sillabe: ["gio",  "co"]    },
  { parola: "libro",   sillabe: ["li",   "bro"]   },
  { parola: "porta",   sillabe: ["por",  "ta"]    },
  { parola: "ponte",   sillabe: ["pon",  "te"]    },
  { parola: "campo",   sillabe: ["cam",  "po"]    },
  { parola: "vento",   sillabe: ["ven",  "to"]    },
  { parola: "notte",   sillabe: ["not",  "te"]    },
  { parola: "letto",   sillabe: ["let",  "to"]    },
  { parola: "mondo",   sillabe: ["mon",  "do"]    },
  { parola: "palla",   sillabe: ["pal",  "la"]    },
  { parola: "stella",  sillabe: ["stel", "la"]    },
  { parola: "mela",    sillabe: ["me",   "la"]    },
  { parola: "pera",    sillabe: ["pe",   "ra"]    },
  { parola: "uva",     sillabe: ["u",    "va"]    },
  { parola: "riso",    sillabe: ["ri",   "so"]    },
  { parola: "ramo",    sillabe: ["ra",   "mo"]    },
  { parola: "rana",    sillabe: ["ra",   "na"]    },
  { parola: "rosa",    sillabe: ["ro",   "sa"]    },
  { parola: "strada",  sillabe: ["stra", "da"]    },
  { parola: "scala",   sillabe: ["sca",  "la"]    },
  { parola: "prato",   sillabe: ["pra",  "to"]    },
  { parola: "drago",   sillabe: ["dra",  "go"]    },
  { parola: "guerra",  sillabe: ["guer", "ra"]    },
  { parola: "terra",   sillabe: ["ter",  "ra"]    },
  { parola: "miele",   sillabe: ["mie",  "le"]    },
  { parola: "chiesa",  sillabe: ["chie", "sa"]    },
  { parola: "orso",    sillabe: ["or",   "so"]    },
  { parola: "erba",    sillabe: ["er",   "ba"]    },
  { parola: "onda",    sillabe: ["on",   "da"]    },
  { parola: "uovo",    sillabe: ["uo",   "vo"]    },
  { parola: "fuoco",   sillabe: ["fuo",  "co"]    },
  { parola: "tazza",   sillabe: ["taz",  "za"]    },
  { parola: "torta",   sillabe: ["tor",  "ta"]    },
  { parola: "arte",    sillabe: ["ar",   "te"]    },
  { parola: "carta",   sillabe: ["car",  "ta"]    },
  { parola: "borsa",   sillabe: ["bor",  "sa"]    },
  { parola: "corpo",   sillabe: ["cor",  "po"]    },
  { parola: "forno",   sillabe: ["for",  "no"]    },
  { parola: "corvo",   sillabe: ["cor",  "vo"]    },
  { parola: "alba",    sillabe: ["al",   "ba"]    },
  { parola: "arco",    sillabe: ["ar",   "co"]    },
  { parola: "palma",   sillabe: ["pal",  "ma"]    },
  { parola: "volpe",   sillabe: ["vol",  "pe"]    },
  { parola: "gallo",   sillabe: ["gal",  "lo"]    },
  { parola: "scarpa",  sillabe: ["scar", "pa"]    },
  { parola: "scudo",   sillabe: ["scu",  "do"]    },
  { parola: "braccio", sillabe: ["brac", "cio"]   },
  { parola: "spalla",  sillabe: ["spal", "la"]    },
  { parola: "suono",   sillabe: ["suo",  "no"]    },
  { parola: "viaggio", sillabe: ["viag", "gio"]   },
  { parola: "raggio",  sillabe: ["rag",  "gio"]   },
  { parola: "figlio",  sillabe: ["fi",   "glio"]  },
  { parola: "foglio",  sillabe: ["fo",   "glio"]  },
  { parola: "specchio",sillabe: ["spec", "chio"]  },
  { parola: "occhio",  sillabe: ["oc",   "chio"]  },
  { parola: "vecchio", sillabe: ["vec",  "chio"]  },
  { parola: "becco",   sillabe: ["bec",  "co"]    },
  { parola: "gamba",   sillabe: ["gam",  "ba"]    },
  { parola: "gonna",   sillabe: ["gon",  "na"]    },
  { parola: "donna",   sillabe: ["don",  "na"]    },
  { parola: "nonno",   sillabe: ["non",  "no"]    },
  { parola: "tonno",   sillabe: ["ton",  "no"]    },
  { parola: "anno",    sillabe: ["an",   "no"]    },
  { parola: "tanto",   sillabe: ["tan",  "to"]    },
  { parola: "pianta",  sillabe: ["pian", "ta"]    },
  { parola: "grano",   sillabe: ["gra",  "no"]    },
  { parola: "piano",   sillabe: ["pia",  "no"]    },
  { parola: "bello",   sillabe: ["bel",  "lo"]    },
  { parola: "buono",   sillabe: ["buo",  "no"]    },
  { parola: "verde",   sillabe: ["ver",  "de"]    },
  { parola: "rosso",   sillabe: ["ros",  "so"]    },
  { parola: "nero",    sillabe: ["ne",   "ro"]    },
  { parola: "giallo",  sillabe: ["gial", "lo"]    },
  { parola: "grigio",  sillabe: ["gri",  "gio"]   },
  { parola: "viola",   sillabe: ["vio",  "la"]    },
  { parola: "nuovo",   sillabe: ["nuo",  "vo"]    },
  { parola: "caldo",   sillabe: ["cal",  "do"]    },
  { parola: "freddo",  sillabe: ["fred", "do"]    },
  { parola: "dolce",   sillabe: ["dol",  "ce"]    },
  { parola: "grande",  sillabe: ["gran", "de"]    },
  { parola: "bene",    sillabe: ["be",   "ne"]    },
  { parola: "male",    sillabe: ["ma",   "le"]    },
  { parola: "sempre",  sillabe: ["sem",  "pre"]   },
  { parola: "presto",  sillabe: ["pre",  "sto"]   },
  { parola: "sette",   sillabe: ["set",  "te"]    },
  { parola: "otto",    sillabe: ["ot",   "to"]    },
  { parola: "dieci",   sillabe: ["die",  "ci"]    },
  { parola: "nove",    sillabe: ["no",   "ve"]    },
  { parola: "quattro", sillabe: ["quat", "tro"]   },
  { parola: "cinque",  sillabe: ["cin",  "que"]   },
  { parola: "forte",   sillabe: ["for",  "te"]    },
  { parola: "porto",   sillabe: ["por",  "to"]    },
  { parola: "forma",   sillabe: ["for",  "ma"]    },
  { parola: "perla",   sillabe: ["per",  "la"]    },
  { parola: "ombra",   sillabe: ["om",   "bra"]   },
  { parola: "nodo",    sillabe: ["no",   "do"]    },
  { parola: "modo",    sillabe: ["mo",   "do"]    },
  { parola: "moto",    sillabe: ["mo",   "to"]    },
  { parola: "foto",    sillabe: ["fo",   "to"]    },
  { parola: "torso",   sillabe: ["tor",  "so"]    },
  { parola: "dente",   sillabe: ["den",  "te"]    },
  { parola: "gente",   sillabe: ["gen",  "te"]    },
  { parola: "mente",   sillabe: ["men",  "te"]    },
  { parola: "tigre",   sillabe: ["ti",   "gre"]   },
  { parola: "mucca",   sillabe: ["muc",  "ca"]    },
  { parola: "ape",     sillabe: ["a",    "pe"]    },
  { parola: "cigno",   sillabe: ["ci",   "gno"]   },
  { parola: "sogno",   sillabe: ["so",   "gno"]   },
  { parola: "legno",   sillabe: ["le",   "gno"]   },
  { parola: "lepre",   sillabe: ["le",   "pre"]   },
  { parola: "pelo",    sillabe: ["pe",   "lo"]    },
  { parola: "velo",    sillabe: ["ve",   "lo"]    },
  { parola: "nebbia",  sillabe: ["neb",  "bia"]   },
  { parola: "fiaba",   sillabe: ["fia",  "ba"]    },
  { parola: "frase",   sillabe: ["fra",  "se"]    },
  { parola: "nonna",   sillabe: ["non",  "na"]    },
  { parola: "burro",   sillabe: ["bur",  "ro"]    },
  { parola: "sacco",   sillabe: ["sac",  "co"]    },
  { parola: "lungo",   sillabe: ["lun",  "go"]    },
  { parola: "fungo",   sillabe: ["fun",  "go"]    },
  { parola: "borgo",   sillabe: ["bor",  "go"]    },
  { parola: "orzo",    sillabe: ["or",   "zo"]    },
  { parola: "cobra",   sillabe: ["co",   "bra"]   },
  { parola: "panda",   sillabe: ["pan",  "da"]    },
  { parola: "tomba",   sillabe: ["tom",  "ba"]    },
  { parola: "mappa",   sillabe: ["map",  "pa"]    },

  // ── TRISILLABE (200 parole) ───────────────────────────────────────────────
  { parola: "bambino",   sillabe: ["bam",  "bi",   "no"]   },
  { parola: "bambina",   sillabe: ["bam",  "bi",   "na"]   },
  { parola: "farfalla",  sillabe: ["far",  "fal",  "la"]   },
  { parola: "cavallo",   sillabe: ["ca",   "val",  "lo"]   },
  { parola: "bambola",   sillabe: ["bam",  "bo",   "la"]   },
  { parola: "formica",   sillabe: ["for",  "mi",   "ca"]   },
  { parola: "uccello",   sillabe: ["uc",   "cel",  "lo"]   },
  { parola: "castello",  sillabe: ["ca",   "stel", "lo"]   },
  { parola: "bottone",   sillabe: ["bot",  "to",   "ne"]   },
  { parola: "colore",    sillabe: ["co",   "lo",   "re"]   },
  { parola: "gelato",    sillabe: ["ge",   "la",   "to"]   },
  { parola: "banana",    sillabe: ["ba",   "na",   "na"]   },
  { parola: "amore",     sillabe: ["a",    "mo",   "re"]   },
  { parola: "amico",     sillabe: ["a",    "mi",   "co"]   },
  { parola: "numero",    sillabe: ["nu",   "me",   "ro"]   },
  { parola: "albero",    sillabe: ["al",   "be",   "ro"]   },
  { parola: "minuto",    sillabe: ["mi",   "nu",   "to"]   },
  { parola: "campana",   sillabe: ["cam",  "pa",   "na"]   },
  { parola: "tavolo",    sillabe: ["ta",   "vo",   "lo"]   },
  { parola: "mattina",   sillabe: ["mat",  "ti",   "na"]   },
  { parola: "sabato",    sillabe: ["sa",   "ba",   "to"]   },
  { parola: "domani",    sillabe: ["do",   "ma",   "ni"]   },
  { parola: "cugino",    sillabe: ["cu",   "gi",   "no"]   },
  { parola: "nipote",    sillabe: ["ni",   "po",   "te"]   },
  { parola: "fratello",  sillabe: ["fra",  "tel",  "lo"]   },
  { parola: "sorella",   sillabe: ["so",   "rel",  "la"]   },
  { parola: "zucchero",  sillabe: ["zuc",  "che",  "ro"]   },
  { parola: "formaggio", sillabe: ["for",  "mag",  "gio"]  },
  { parola: "spaghetti", sillabe: ["spa",  "ghet", "ti"]   },
  { parola: "panino",    sillabe: ["pa",   "ni",   "no"]   },
  { parola: "biscotto",  sillabe: ["bi",   "scot", "to"]   },
  { parola: "merenda",   sillabe: ["me",   "ren",  "da"]   },
  { parola: "giraffa",   sillabe: ["gi",   "raf",  "fa"]   },
  { parola: "leone",     sillabe: ["le",   "o",    "ne"]   },
  { parola: "cammello",  sillabe: ["cam",  "mel",  "lo"]   },
  { parola: "gorilla",   sillabe: ["go",   "ril",  "la"]   },
  { parola: "coniglio",  sillabe: ["co",   "ni",   "glio"] },
  { parola: "serpente",  sillabe: ["ser",  "pen",  "te"]   },
  { parola: "maiale",    sillabe: ["ma",   "ia",   "le"]   },
  { parola: "pecora",    sillabe: ["pe",   "co",   "ra"]   },
  { parola: "asino",     sillabe: ["a",    "si",   "no"]   },
  { parola: "gallina",   sillabe: ["gal",  "li",   "na"]   },
  { parola: "pinguino",  sillabe: ["pin",  "gui",  "no"]   },
  { parola: "balena",    sillabe: ["ba",   "le",   "na"]   },
  { parola: "castoro",   sillabe: ["ca",   "sto",  "ro"]   },
  { parola: "capriolo",  sillabe: ["ca",   "prio", "lo"]   },
  { parola: "agosto",    sillabe: ["a",    "go",   "sto"]  },
  { parola: "ottobre",   sillabe: ["ot",   "to",   "bre"]  },
  { parola: "novembre",  sillabe: ["no",   "vem",  "bre"]  },
  { parola: "dicembre",  sillabe: ["di",   "cem",  "bre"]  },
  { parola: "gennaio",   sillabe: ["gen",  "na",   "io"]   },
  { parola: "febbraio",  sillabe: ["feb",  "bra",  "io"]   },
  { parola: "aprile",    sillabe: ["a",    "pri",  "le"]   },
  { parola: "settembre", sillabe: ["set",  "tem",  "bre"]  },
  { parola: "lunedì",    sillabe: ["lu",   "ne",   "dì"]   },
  { parola: "martedì",   sillabe: ["mar",  "te",   "dì"]   },
  { parola: "giovedì",   sillabe: ["gio",  "ve",   "dì"]   },
  { parola: "venerdì",   sillabe: ["ve",   "ner",  "dì"]   },
  { parola: "macchina",  sillabe: ["mac",  "chi",  "na"]   },
  { parola: "motore",    sillabe: ["mo",   "to",   "re"]   },
  { parola: "ombrello",  sillabe: ["om",   "brel", "lo"]   },
  { parola: "cappello",  sillabe: ["cap",  "pel",  "lo"]   },
  { parola: "maglietta", sillabe: ["ma",   "gliet","ta"]   },
  { parola: "vestito",   sillabe: ["ve",   "sti",  "to"]   },
  { parola: "stivale",   sillabe: ["sti",  "va",   "le"]   },
  { parola: "cintura",   sillabe: ["cin",  "tu",   "ra"]   },
  { parola: "cappotto",  sillabe: ["cap",  "pot",  "to"]   },
  { parola: "calzino",   sillabe: ["cal",  "zi",   "no"]   },
  { parola: "pigiama",   sillabe: ["pi",   "gia",  "ma"]   },
  { parola: "coperta",   sillabe: ["co",   "per",  "ta"]   },
  { parola: "cuscino",   sillabe: ["cu",   "sci",  "no"]   },
  { parola: "armadio",   sillabe: ["ar",   "ma",   "dio"]  },
  { parola: "divano",    sillabe: ["di",   "va",   "no"]   },
  { parola: "cucina",    sillabe: ["cu",   "ci",   "na"]   },
  { parola: "camera",    sillabe: ["ca",   "me",   "ra"]   },
  { parola: "salotto",   sillabe: ["sa",   "lot",  "to"]   },
  { parola: "giardino",  sillabe: ["giar", "di",   "no"]   },
  { parola: "matita",    sillabe: ["ma",   "ti",   "ta"]   },
  { parola: "quaderno",  sillabe: ["qua",  "der",  "no"]   },
  { parola: "forbici",   sillabe: ["for",  "bi",   "ci"]   },
  { parola: "pennello",  sillabe: ["pen",  "nel",  "lo"]   },
  { parola: "disegno",   sillabe: ["di",   "se",   "gno"]  },
  { parola: "musica",    sillabe: ["mu",   "si",   "ca"]   },
  { parola: "chitarra",  sillabe: ["chi",  "tar",  "ra"]   },
  { parola: "violino",   sillabe: ["vio",  "li",   "no"]   },
  { parola: "cantante",  sillabe: ["can",  "tan",  "te"]   },
  { parola: "attore",    sillabe: ["at",   "to",   "re"]   },
  { parola: "dottore",   sillabe: ["dot",  "to",   "re"]   },
  { parola: "maestro",   sillabe: ["ma",   "e",    "stro"] },
  { parola: "medico",    sillabe: ["me",   "di",   "co"]   },
  { parola: "pompiere",  sillabe: ["pom",  "pie",  "re"]   },
  { parola: "soldato",   sillabe: ["sol",  "da",   "to"]   },
  { parola: "natura",    sillabe: ["na",   "tu",   "ra"]   },
  { parola: "montagna",  sillabe: ["mon",  "ta",   "gna"]  },
  { parola: "collina",   sillabe: ["col",  "li",   "na"]   },
  { parola: "foresta",   sillabe: ["fo",   "re",   "sta"]  },
  { parola: "vulcano",   sillabe: ["vul",  "ca",   "no"]   },
  { parola: "pianeta",   sillabe: ["pia",  "ne",   "ta"]   },
  { parola: "cometa",    sillabe: ["co",   "me",   "ta"]   },
  { parola: "undici",    sillabe: ["un",   "di",   "ci"]   },
  { parola: "dodici",    sillabe: ["do",   "di",   "ci"]   },
  { parola: "tredici",   sillabe: ["tre",  "di",   "ci"]   },
  { parola: "quindici",  sillabe: ["quin", "di",   "ci"]   },
  { parola: "sedici",    sillabe: ["se",   "di",   "ci"]   },
  { parola: "insieme",   sillabe: ["in",   "sie",  "me"]   },
  { parola: "davanti",   sillabe: ["da",   "van",  "ti"]   },
  { parola: "intorno",   sillabe: ["in",   "tor",  "no"]   },
  { parola: "adesso",    sillabe: ["a",    "des",  "so"]   },
  { parola: "subito",    sillabe: ["su",   "bi",   "to"]   },
  { parola: "ancora",    sillabe: ["an",   "co",   "ra"]   },
  { parola: "ginocchio", sillabe: ["gi",   "noc",  "chio"] },
  { parola: "orecchio",  sillabe: ["o",    "rec",  "chio"] },
  { parola: "sorriso",   sillabe: ["sor",  "ri",   "so"]   },
  { parola: "stomaco",   sillabe: ["sto",  "ma",   "co"]   },
  { parola: "cervello",  sillabe: ["cer",  "vel",  "lo"]   },
  { parola: "carota",    sillabe: ["ca",   "ro",   "ta"]   },
  { parola: "cipolla",   sillabe: ["ci",   "pol",  "la"]   },
  { parola: "melone",    sillabe: ["me",   "lo",   "ne"]   },
  { parola: "fragola",   sillabe: ["fra",  "go",   "la"]   },
  { parola: "lampone",   sillabe: ["lam",  "po",   "ne"]   },
  { parola: "ciliegia",  sillabe: ["ci",   "lie",  "gia"]  },
  { parola: "nocciola",  sillabe: ["noc",  "cio",  "la"]   },
  { parola: "castagna",  sillabe: ["ca",   "sta",  "gna"]  },
  { parola: "fagiolo",   sillabe: ["fa",   "gio",  "lo"]   },
  { parola: "pisello",   sillabe: ["pi",   "sel",  "lo"]   },
  { parola: "padella",   sillabe: ["pa",   "del",  "la"]   },
  { parola: "bicchiere", sillabe: ["bic",  "chie", "re"]   },
  { parola: "principe",  sillabe: ["prin", "ci",   "pe"]   },
  { parola: "fantasma",  sillabe: ["fan",  "ta",   "sma"]  },
  { parola: "gigante",   sillabe: ["gi",   "gan",  "te"]   },
  { parola: "ragazzo",   sillabe: ["ra",   "gaz",  "zo"]   },
  { parola: "ragazza",   sillabe: ["ra",   "gaz",  "za"]   },
  { parola: "giovane",   sillabe: ["gio",  "va",   "ne"]   },
  { parola: "amica",     sillabe: ["a",    "mi",   "ca"]   },
  { parola: "palazzo",   sillabe: ["pa",   "laz",  "zo"]   },
  { parola: "villaggio", sillabe: ["vil",  "lag",  "gio"]  },
  { parola: "regione",   sillabe: ["re",   "gio",  "ne"]   },
  { parola: "fortuna",   sillabe: ["for",  "tu",   "na"]   },
  { parola: "segreto",   sillabe: ["se",   "gre",  "to"]   },
  { parola: "sorpresa",  sillabe: ["sor",  "pre",  "sa"]   },
  { parola: "regalo",    sillabe: ["re",   "ga",   "lo"]   },
  { parola: "partita",   sillabe: ["par",  "ti",   "ta"]   },
  { parola: "pallone",   sillabe: ["pal",  "lo",   "ne"]   },
  { parola: "campione",  sillabe: ["cam",  "pio",  "ne"]   },
  { parola: "delfino",   sillabe: ["del",  "fi",   "no"]   },
  { parola: "lumaca",    sillabe: ["lu",   "ma",   "ca"]   },
  { parola: "sentiero",  sillabe: ["sen",  "tie",  "ro"]   },
  { parola: "cammino",   sillabe: ["cam",  "mi",   "no"]   },
  { parola: "corallo",   sillabe: ["co",   "ral",  "lo"]   },
  { parola: "medusa",    sillabe: ["me",   "du",   "sa"]   },
  { parola: "pattino",   sillabe: ["pat",  "ti",   "no"]   },
  { parola: "nuvola",    sillabe: ["nu",   "vo",   "la"]   },
  { parola: "grandine",  sillabe: ["gran", "di",   "ne"]   },
  { parola: "folgore",   sillabe: ["fol",  "go",   "re"]   },
  { parola: "ciclone",   sillabe: ["ci",   "clo",  "ne"]   },
  { parola: "stagione",  sillabe: ["sta",  "gio",  "ne"]   },
  { parola: "inverno",   sillabe: ["in",   "ver",  "no"]   },
  { parola: "autunno",   sillabe: ["au",   "tun",  "no"]   },
  { parola: "estate",    sillabe: ["e",    "sta",  "te"]   },
  { parola: "tempesta",  sillabe: ["tem",  "pe",   "sta"]  },
  { parola: "fulmine",   sillabe: ["ful",  "mi",   "ne"]   },
  { parola: "silenzio",  sillabe: ["si",   "len",  "zio"]  },
  { parola: "rumore",    sillabe: ["ru",   "mo",   "re"]   },
  { parola: "profumo",   sillabe: ["pro",  "fu",   "mo"]   },
  { parola: "odore",     sillabe: ["o",    "do",   "re"]   },
  { parola: "sapore",    sillabe: ["sa",   "po",   "re"]   },
  { parola: "calore",    sillabe: ["ca",   "lo",   "re"]   },
  { parola: "dolciumi",  sillabe: ["dol",  "ciu",  "mi"]   },
  { parola: "ricotta",   sillabe: ["ri",   "cot",  "ta"]   },
  { parola: "polenta",   sillabe: ["po",   "len",  "ta"]   },
  { parola: "minestra",  sillabe: ["mi",   "ne",   "stra"] },
  { parola: "gambero",   sillabe: ["gam",  "be",   "ro"]   },
  { parola: "libertà",   sillabe: ["li",   "ber",  "tà"]   },
  { parola: "verità",    sillabe: ["ve",   "ri",   "tà"]   },
  { parola: "silaba",    sillabe: ["sil",  "la",   "ba"]   },
  { parola: "parola",    sillabe: ["pa",   "ro",   "la"]   },
  { parola: "pagina",    sillabe: ["pa",   "gi",   "na"]   },
  { parola: "persona",   sillabe: ["per",  "so",   "na"]   },
  { parola: "governo",   sillabe: ["go",   "ver",  "no"]   },
  { parola: "popolo",    sillabe: ["po",   "po",   "lo"]   },
  { parola: "piccolo",   sillabe: ["pic",  "co",   "lo"]   },
  { parola: "facile",    sillabe: ["fa",   "ci",   "le"]   },
  { parola: "magico",    sillabe: ["ma",   "gi",   "co"]   },
  { parola: "comico",    sillabe: ["co",   "mi",   "co"]   },
  { parola: "libero",    sillabe: ["li",   "be",   "ro"]   },
  { parola: "sicuro",    sillabe: ["si",   "cu",   "ro"]   },
  { parola: "veloce",    sillabe: ["ve",   "lo",   "ce"]   },
  { parola: "vicino",    sillabe: ["vi",   "ci",   "no"]   },
  { parola: "lontano",   sillabe: ["lon",  "ta",   "no"]   },
  { parola: "indietro",  sillabe: ["in",   "die",  "tro"]  },
  { parola: "avanti",    sillabe: ["a",    "van",  "ti"]   },
  { parola: "rondine",   sillabe: ["ron",  "di",   "ne"]   },
  { parola: "polizia",   sillabe: ["po",   "li",   "zia"]  },
  { parola: "dentista",  sillabe: ["den",  "ti",   "sta"]  },
  { parola: "pilota",    sillabe: ["pi",   "lo",   "ta"]   },

  // ── QUADRISILLABE (150 parole) ────────────────────────────────────────────
  { parola: "tartaruga",    sillabe: ["tar",  "ta",   "ru",   "ga"]   },
  { parola: "elefante",     sillabe: ["e",    "le",   "fan",  "te"]   },
  { parola: "pappagallo",   sillabe: ["pap",  "pa",   "gal",  "lo"]   },
  { parola: "coccodrillo",  sillabe: ["coc",  "co",   "dril", "lo"]   },
  { parola: "cioccolato",   sillabe: ["cioc", "co",   "la",   "to"]   },
  { parola: "pomodoro",     sillabe: ["po",   "mo",   "do",   "ro"]   },
  { parola: "animale",      sillabe: ["a",    "ni",   "ma",   "le"]   },
  { parola: "biblioteca",   sillabe: ["bi",   "blio", "te",   "ca"]   },
  { parola: "ospedale",     sillabe: ["o",    "spe",  "da",   "le"]   },
  { parola: "telefono",     sillabe: ["te",   "le",   "fo",   "no"]   },
  { parola: "bicicletta",   sillabe: ["bi",   "ci",   "clet", "ta"]   },
  { parola: "motorino",     sillabe: ["mo",   "to",   "ri",   "no"]   },
  { parola: "ombrellone",   sillabe: ["om",   "brel", "lo",   "ne"]   },
  { parola: "orologio",     sillabe: ["o",    "ro",   "lo",   "gio"]  },
  { parola: "personaggio",  sillabe: ["per",  "so",   "nag",  "gio"]  },
  { parola: "avventura",    sillabe: ["av",   "ven",  "tu",   "ra"]   },
  { parola: "fantastico",   sillabe: ["fan",  "ta",   "sti",  "co"]   },
  { parola: "magnifico",    sillabe: ["ma",   "gni",  "fi",   "co"]   },
  { parola: "terribile",    sillabe: ["ter",  "ri",   "bi",   "le"]   },
  { parola: "meraviglia",   sillabe: ["me",   "ra",   "vi",   "glia"] },
  { parola: "divertente",   sillabe: ["di",   "ver",  "ten",  "te"]   },
  { parola: "silenzioso",   sillabe: ["si",   "len",  "zio",  "so"]   },
  { parola: "rumoroso",     sillabe: ["ru",   "mo",   "ro",   "so"]   },
  { parola: "generoso",     sillabe: ["ge",   "ne",   "ro",   "so"]   },
  { parola: "coraggioso",   sillabe: ["co",   "rag",  "gio",  "so"]   },
  { parola: "misterioso",   sillabe: ["mi",   "ste",  "rio",  "so"]   },
  { parola: "talentuoso",  sillabe: ["ta",   "len",  "tuo",  "so"]   },
  { parola: "difficile",    sillabe: ["dif",  "fi",   "ci",   "le"]   },
  { parola: "possibile",    sillabe: ["pos",  "si",   "bi",   "le"]   },
  { parola: "importante",   sillabe: ["im",   "por",  "tan",  "te"]   },
  { parola: "giocattolo",   sillabe: ["gio",  "cat",  "to",   "lo"]   },
  { parola: "plastilina",   sillabe: ["pla",  "sti",  "li",   "na"]   },
  { parola: "costruzione",  sillabe: ["co",   "stru", "zio",  "ne"]   },
  { parola: "porcospino",  sillabe: ["por",  "co",   "spi",  "no"]   },
  { parola: "videogioco",   sillabe: ["vi",   "deo",  "gio",  "co"]   },
  { parola: "coccinella",   sillabe: ["coc",  "ci",   "nel",  "la"]   },
  { parola: "lucertola",    sillabe: ["lu",   "cer",  "to",   "la"]   },
  { parola: "scoiattolo",   sillabe: ["sco",  "iat",  "to",   "lo"]   },
  { parola: "ippocampo",    sillabe: ["ip",   "po",   "cam",  "po"]   },
  { parola: "leopardo",     sillabe: ["le",   "o",    "par",  "do"]   },
  { parola: "girasole",     sillabe: ["gi",   "ra",   "so",   "le"]   },
  { parola: "dinosauro",    sillabe: ["di",   "no",   "sau",  "ro"]   },
  { parola: "albicocca",    sillabe: ["al",   "bi",   "coc",  "ca"]   },
  { parola: "caramella",    sillabe: ["ca",   "ra",   "mel",  "la"]   },
  { parola: "limonata",     sillabe: ["li",   "mo",   "na",   "ta"]   },
  { parola: "aranciata",    sillabe: ["a",    "ran",  "cia",  "ta"]   },
  { parola: "cioccolata",   sillabe: ["cioc", "co",   "la",   "ta"]   },
  { parola: "insalata",     sillabe: ["in",   "sa",   "la",   "ta"]   },
  { parola: "mozzarella",   sillabe: ["moz",  "za",   "rel",  "la"]   },
  { parola: "provolone",    sillabe: ["pro",  "vo",   "lo",   "ne"]   },
  { parola: "pecorino",     sillabe: ["pe",   "co",   "ri",   "no"]   },
  { parola: "parmigiano",   sillabe: ["par",  "mi",   "gia",  "no"]   },
  { parola: "amaretto",     sillabe: ["a",    "ma",   "ret",  "to"]   },
  { parola: "tiramisù",     sillabe: ["ti",   "ra",   "mi",   "sù"]   },
  { parola: "panettone",    sillabe: ["pa",   "net",  "to",   "ne"]   },
  { parola: "tagliatelle",  sillabe: ["ta",   "glia", "tel",  "le"]   },
  { parola: "maccheroni",   sillabe: ["mac",  "che",  "ro",   "ni"]   },
  { parola: "rigatoni",     sillabe: ["ri",   "ga",   "to",   "ni"]   },
  { parola: "carbonara",    sillabe: ["car",  "bo",   "na",   "ra"]   },
  { parola: "bolognese",    sillabe: ["bo",   "lo",   "gne",  "se"]   },
  { parola: "terremoto",    sillabe: ["ter",  "re",   "mo",   "to"]   },
  { parola: "panorama",     sillabe: ["pa",   "no",   "ra",   "ma"]   },
  { parola: "orizzonte",    sillabe: ["o",    "riz",  "zon",  "te"]   },
  { parola: "campanile",    sillabe: ["cam",  "pa",   "ni",   "le"]   },
  { parola: "atmosfera",    sillabe: ["at",   "mos",  "fe",   "ra"]   },
  { parola: "telescopio",   sillabe: ["te",   "le",   "sco",  "pio"]  },
  { parola: "satellite",    sillabe: ["sa",   "tel",  "li",   "te"]   },
  { parola: "asteroide",    sillabe: ["a",    "ste",  "roi",  "de"]   },
  { parola: "planetario",   sillabe: ["pla",  "ne",   "ta",   "rio"]  },
  { parola: "oceano",       sillabe: ["o",    "ce",   "a",    "no"]   },
  { parola: "italiano",     sillabe: ["i",    "ta",   "lia",  "no"]   },
  { parola: "nazionale",    sillabe: ["na",   "zio",  "na",   "le"]   },
  { parola: "tradizione",   sillabe: ["tra",  "di",   "zio",  "ne"]   },
  { parola: "produzione",   sillabe: ["pro",  "du",   "zio",  "ne"]   },
  { parola: "soluzione",    sillabe: ["so",   "lu",   "zio",  "ne"]   },
  { parola: "collezione",   sillabe: ["col",  "le",   "zio",  "ne"]   },
  { parola: "posizione",    sillabe: ["po",   "si",   "zio",  "ne"]   },
  { parola: "attenzione",   sillabe: ["at",   "ten",  "zio",  "ne"]   },
  { parola: "direzione",    sillabe: ["di",   "re",   "zio",  "ne"]   },
  { parola: "situazione",   sillabe: ["si",   "tua",  "zio",  "ne"]   },
  { parola: "direttore",    sillabe: ["di",   "ret",  "to",   "re"]   },
  { parola: "professore",   sillabe: ["pro",  "fes",  "so",   "re"]   },
  { parola: "infermiere",   sillabe: ["in",   "fer",  "mie",  "re"]   },
  { parola: "cameriere",    sillabe: ["ca",   "me",   "rie",  "re"]   },
  { parola: "giardiniere",  sillabe: ["giar", "di",   "nie",  "re"]   },
  { parola: "astronauta",   sillabe: ["a",    "stro", "nau",  "ta"]   },
  { parola: "capitano",     sillabe: ["ca",   "pi",   "ta",   "no"]   },
  { parola: "ingegnere",    sillabe: ["in",   "ge",   "gne",  "re"]   },
  { parola: "avvocato",     sillabe: ["av",   "vo",   "ca",   "to"]   },
  { parola: "architetto",   sillabe: ["ar",   "chi",  "tet",  "to"]   },
  { parola: "farmacista",   sillabe: ["far",  "ma",   "ci",   "sta"]  },
  { parola: "psicologo",    sillabe: ["psi",  "co",   "lo",   "go"]   },
  { parola: "carosello",    sillabe: ["ca",   "ro",   "sel",  "lo"]   },
  { parola: "ballerina",    sillabe: ["bal",  "le",   "ri",   "na"]   },
  { parola: "calciatore",   sillabe: ["cal",  "cia",  "to",   "re"]   },
  { parola: "campionato",   sillabe: ["cam",  "pio",  "na",   "to"]   },
  { parola: "portafoglio",  sillabe: ["por",  "ta",   "fo",   "glio"] },
  { parola: "calendario",   sillabe: ["ca",   "len",  "da",   "rio"]  },
  { parola: "minestrone",   sillabe: ["mi",   "ne",   "stro", "ne"]   },
  { parola: "calamaro",     sillabe: ["ca",   "la",   "ma",   "ro"]   },
  { parola: "mammifero",    sillabe: ["mam",  "mi",   "fe",   "ro"]   },
  { parola: "primavera",    sillabe: ["pri",  "ma",   "ve",   "ra"]   },
  { parola: "temporale",    sillabe: ["tem",  "po",   "ra",   "le"]   },
  { parola: "carnevale",    sillabe: ["car",  "ne",   "va",   "le"]   },
  { parola: "felicità",     sillabe: ["fe",   "li",   "ci",   "tà"]   },
  { parola: "necessario",   sillabe: ["ne",   "ces",  "sa",   "rio"]  },
  { parola: "specialmente", sillabe: ["spe",  "cial", "men",  "te"]   },
  { parola: "impaziente",   sillabe: ["im",   "pa",   "zien", "te"]   },
  { parola: "spaventato",   sillabe: ["spa",  "ven",  "ta",   "to"]   },
  { parola: "sorprendente", sillabe: ["sor",  "pren", "den",  "te"]   },
  { parola: "chiaramente",  sillabe: ["chia", "ra",   "men",  "te"]   },
  { parola: "rispettoso",   sillabe: ["ri",   "spet", "to",   "so"]   },
  { parola: "colorato",     sillabe: ["co",   "lo",   "ra",   "to"]   },
  { parola: "profumato",    sillabe: ["pro",  "fu",   "ma",   "to"]   },
  { parola: "ridicolo",     sillabe: ["ri",   "di",   "co",   "lo"]   },
  { parola: "attività",     sillabe: ["at",   "ti",   "vi",   "tà"]   },
  { parola: "difficoltà",   sillabe: ["dif",  "fi",   "col",  "tà"]   },
  { parola: "curiosità",    sillabe: ["cu",   "rio",  "si",   "tà"]   },
  { parola: "allegria",     sillabe: ["al",   "le",   "gri",  "a"]    },
  { parola: "nostalgia",    sillabe: ["no",   "stal", "gi",   "a"]    },
  { parola: "fantasia",     sillabe: ["fan",  "ta",   "si",   "a"]    },
  { parola: "melodia",      sillabe: ["me",   "lo",   "di",   "a"]    },
  { parola: "sinfonia",     sillabe: ["sin",  "fo",   "ni",   "a"]    },
  { parola: "poesia",       sillabe: ["po",   "e",    "si",   "a"]    },
  { parola: "energia",      sillabe: ["e",    "ner",  "gi",   "a"]    },
  { parola: "repubblica",   sillabe: ["re",   "pub",  "bli",  "ca"]   },
  { parola: "democrazia",   sillabe: ["de",   "mo",   "cra",  "zia"]  },
  { parola: "unicorno",     sillabe: ["u",    "ni",   "cor",  "no"]   },
  { parola: "dragonessa",   sillabe: ["dra",  "go",   "nes",  "sa"]   },
  { parola: "cavaliere",    sillabe: ["ca",   "va",   "lie",  "re"]   },
  { parola: "principessa",  sillabe: ["prin", "ci",   "pes",  "sa"]   },
  { parola: "ossobuco",     sillabe: ["os",   "so",   "bu",   "co"]   },
  { parola: "pasticceria",  sillabe: ["pa",   "stic", "ce",   "ria"]  },
  { parola: "trattoria",    sillabe: ["trat", "to",   "ri",   "a"]    },
  { parola: "paradiso",     sillabe: ["pa",   "ra",   "di",   "so"]   },
  { parola: "binocolo",     sillabe: ["bi",   "noc",  "co",   "lo"]   },
  { parola: "catalogo",     sillabe: ["ca",   "ta",   "lo",   "go"]   },
  { parola: "semaforo",     sillabe: ["se",   "ma",   "fo",   "ro"]   },
  { parola: "galassia",     sillabe: ["ga",   "las",  "si",   "a"]    },
  { parola: "gondoliere",   sillabe: ["gon",  "do",   "lie",  "re"]   },
  { parola: "cittadino",    sillabe: ["cit",  "ta",   "di",   "no"]   },
  { parola: "contadino",    sillabe: ["con",  "ta",   "di",   "no"]   },
  { parola: "falegname",    sillabe: ["fa",   "le",   "gna",  "me"]   },
  { parola: "patrimonio",   sillabe: ["pa",   "tri",  "mo",   "nio"]  },
];
