// 500 parole italiane comuni suddivise per numero di sillabe
// Formato: { parola: "PANE", sillabe: ["PA", "NE"] }

const parole = [

  // ── BISILLABE (150 parole) ────────────────────────────────────────────────
  { parola: "PANE",    sillabe: ["PA",   "NE"]    },
  { parola: "CASA",    sillabe: ["CA",   "SA"]    },
  { parola: "MARE",    sillabe: ["MA",   "RE"]    },
  { parola: "SOLE",    sillabe: ["SO",   "LE"]    },
  { parola: "LUNA",    sillabe: ["LU",   "NA"]    },
  { parola: "FIORE",   sillabe: ["FIO",  "RE"]    },
  { parola: "CIELO",   sillabe: ["CIE",  "LO"]    },
  { parola: "PIEDE",   sillabe: ["PIE",  "DE"]    },
  { parola: "MANO",    sillabe: ["MA",   "NO"]    },
  { parola: "BOCCA",   sillabe: ["BOC",  "CA"]    },
  { parola: "VITA",    sillabe: ["VI",   "TA"]    },
  { parola: "TEMPO",   sillabe: ["TEM",  "PO"]    },
  { parola: "CANE",    sillabe: ["CA",   "NE"]    },
  { parola: "GATTO",   sillabe: ["GAT",  "TO"]    },
  { parola: "PESCE",   sillabe: ["PE",   "SCE"]   },
  { parola: "LATTE",   sillabe: ["LAT",  "TE"]    },
  { parola: "ACQUA",   sillabe: ["AC",   "QUA"]   },
  { parola: "PAPÀ",    sillabe: ["PA",   "PÀ"]    },
  { parola: "MAMMA",   sillabe: ["MAM",  "MA"]    },
  { parola: "GIOCO",   sillabe: ["GIO",  "CO"]    },
  { parola: "LIBRO",   sillabe: ["LI",   "BRO"]   },
  { parola: "PORTA",   sillabe: ["POR",  "TA"]    },
  { parola: "PONTE",   sillabe: ["PON",  "TE"]    },
  { parola: "CAMPO",   sillabe: ["CAM",  "PO"]    },
  { parola: "VENTO",   sillabe: ["VEN",  "TO"]    },
  { parola: "NOTTE",   sillabe: ["NOT",  "TE"]    },
  { parola: "LETTO",   sillabe: ["LET",  "TO"]    },
  { parola: "MONDO",   sillabe: ["MON",  "DO"]    },
  { parola: "PALLA",   sillabe: ["PAL",  "LA"]    },
  { parola: "STELLA",  sillabe: ["STEL", "LA"]    },
  { parola: "MELA",    sillabe: ["ME",   "LA"]    },
  { parola: "PERA",    sillabe: ["PE",   "RA"]    },
  { parola: "UVA",     sillabe: ["U",    "VA"]    },
  { parola: "RISO",    sillabe: ["RI",   "SO"]    },
  { parola: "RAMO",    sillabe: ["RA",   "MO"]    },
  { parola: "RANA",    sillabe: ["RA",   "NA"]    },
  { parola: "ROSA",    sillabe: ["RO",   "SA"]    },
  { parola: "STRADA",  sillabe: ["STRA", "DA"]    },
  { parola: "SCALA",   sillabe: ["SCA",  "LA"]    },
  { parola: "PRATO",   sillabe: ["PRA",  "TO"]    },
  { parola: "DRAGO",   sillabe: ["DRA",  "GO"]    },
  { parola: "GUERRA",  sillabe: ["GUER", "RA"]    },
  { parola: "TERRA",   sillabe: ["TER",  "RA"]    },
  { parola: "MIELE",   sillabe: ["MIE",  "LE"]    },
  { parola: "CHIESA",  sillabe: ["CHIE", "SA"]    },
  { parola: "ORSO",    sillabe: ["OR",   "SO"]    },
  { parola: "ERBA",    sillabe: ["ER",   "BA"]    },
  { parola: "ONDA",    sillabe: ["ON",   "DA"]    },
  { parola: "UOVO",    sillabe: ["UO",   "VO"]    },
  { parola: "FUOCO",   sillabe: ["FUO",  "CO"]    },
  { parola: "TAZZA",   sillabe: ["TAZ",  "ZA"]    },
  { parola: "TORTA",   sillabe: ["TOR",  "TA"]    },
  { parola: "ARTE",    sillabe: ["AR",   "TE"]    },
  { parola: "CARTA",   sillabe: ["CAR",  "TA"]    },
  { parola: "BORSA",   sillabe: ["BOR",  "SA"]    },
  { parola: "CORPO",   sillabe: ["COR",  "PO"]    },
  { parola: "FORNO",   sillabe: ["FOR",  "NO"]    },
  { parola: "CORVO",   sillabe: ["COR",  "VO"]    },
  { parola: "ALBA",    sillabe: ["AL",   "BA"]    },
  { parola: "ARCO",    sillabe: ["AR",   "CO"]    },
  { parola: "PALMA",   sillabe: ["PAL",  "MA"]    },
  { parola: "VOLPE",   sillabe: ["VOL",  "PE"]    },
  { parola: "GALLO",   sillabe: ["GAL",  "LO"]    },
  { parola: "SCARPA",  sillabe: ["SCAR", "PA"]    },
  { parola: "SCUDO",   sillabe: ["SCU",  "DO"]    },
  { parola: "BRACCIO", sillabe: ["BRAC", "CIO"]   },
  { parola: "SPALLA",  sillabe: ["SPAL", "LA"]    },
  { parola: "SUONO",   sillabe: ["SUO",  "NO"]    },
  { parola: "VIAGGIO", sillabe: ["VIAG", "GIO"]   },
  { parola: "RAGGIO",  sillabe: ["RAG",  "GIO"]   },
  { parola: "FIGLIO",  sillabe: ["FI",   "GLIO"]  },
  { parola: "FOGLIO",  sillabe: ["FO",   "GLIO"]  },
  { parola: "SPECCHIO",sillabe: ["SPEC", "CHIO"]  },
  { parola: "OCCHIO",  sillabe: ["OC",   "CHIO"]  },
  { parola: "VECCHIO", sillabe: ["VEC", "CHIO"]  },
  { parola: "BECCO",   sillabe: ["BEC",  "CO"]    },
  { parola: "GAMBA",   sillabe: ["GAM",  "BA"]    },
  { parola: "GONNA",   sillabe: ["GON",  "NA"]    },
  { parola: "DONNA",   sillabe: ["DON",  "NA"]    },
  { parola: "NONNO",   sillabe: ["NON",  "NO"]    },
  { parola: "TONNO",   sillabe: ["TON",  "NO"]    },
  { parola: "ANNO",    sillabe: ["AN",   "NO"]    },
  { parola: "TANTO",   sillabe: ["TAN",  "TO"]    },
  { parola: "PIANTA",  sillabe: ["PIAN", "TA"]    },
  { parola: "GRANO",   sillabe: ["GRA",  "NO"]    },
  { parola: "PIANO",   sillabe: ["PIA",  "NO"]    },
  { parola: "BELLO",   sillabe: ["BEL",  "LO"]    },
  { parola: "BUONO",   sillabe: ["BUO",  "NO"]    },
  { parola: "VERDE",   sillabe: ["VER",  "DE"]    },
  { parola: "ROSSO",   sillabe: ["ROS",  "SO"]    },
  { parola: "NERO",    sillabe: ["NE",   "RO"]    },
  { parola: "GIALLO",  sillabe: ["GIAL", "LO"]    },
  { parola: "GRIGIO",  sillabe: ["GRI",  "GIO"]   },
  { parola: "VIOLA",   sillabe: ["VIO",  "LA"]    },
  { parola: "NUOVO",   sillabe: ["NUO",  "VO"]    },
  { parola: "CALDO",   sillabe: ["CAL",  "DO"]    },
  { parola: "FREDDO",  sillabe: ["FRED", "DO"]    },
  { parola: "DOLCE",   sillabe: ["DOL",  "CE"]    },
  { parola: "GRANDE",  sillabe: ["GRAN", "DE"]    },
  { parola: "BENE",    sillabe: ["BE",   "NE"]    },
  { parola: "MALE",    sillabe: ["MA",   "LE"]    },
  { parola: "SEMPRE",  sillabe: ["SEM",  "PRE"]   },
  { parola: "PRESTO",  sillabe: ["PRE",  "STO"]   },
  { parola: "SETTE",   sillabe: ["SET",  "TE"]    },
  { parola: "OTTO",    sillabe: ["OT",   "TO"]    },
  { parola: "DIECI",   sillabe: ["DIE",  "CI"]    },
  { parola: "NOVE",    sillabe: ["NO",   "VE"]    },
  { parola: "QUATTRO", sillabe: ["QUAT", "TRO"]   },
  { parola: "CINQUE",  sillabe: ["CIN",  "QUE"]   },
  { parola: "FORTE",   sillabe: ["FOR",  "TE"]    },
  { parola: "PORTO",   sillabe: ["POR",  "TO"]    },
  { parola: "FORMA",   sillabe: ["FOR",  "MA"]    },
  { parola: "PERLA",   sillabe: ["PER",  "LA"]    },
  { parola: "OMBRA",   sillabe: ["OM",   "BRA"]   },
  { parola: "NODO",    sillabe: ["NO",   "DO"]    },
  { parola: "MODO",    sillabe: ["MO",   "DO"]    },
  { parola: "MOTO",    sillabe: ["MO",   "TO"]    },
  { parola: "FOTO",    sillabe: ["FO",   "TO"]    },
  { parola: "TORSO",   sillabe: ["TOR",  "SO"]    },
  { parola: "DENTE",   sillabe: ["DEN",  "TE"]    },
  { parola: "GENTE",   sillabe: ["GEN",  "TE"]    },
  { parola: "MENTE",   sillabe: ["MEN",  "TE"]    },
  { parola: "TIGRE",   sillabe: ["TI",   "GRE"]   },
  { parola: "MUCCA",   sillabe: ["MUC",  "CA"]    },
  { parola: "APE",     sillabe: ["A",    "PE"]    },
  { parola: "CIGNO",   sillabe: ["CI",   "GNO"]   },
  { parola: "SOGNO",   sillabe: ["SO",   "GNO"]   },
  { parola: "LEGNO",   sillabe: ["LE",   "GNO"]   },
  { parola: "LEPRE",   sillabe: ["LE",   "PRE"]   },
  { parola: "PELO",    sillabe: ["PE",   "LO"]    },
  { parola: "VELO",    sillabe: ["VE",   "LO"]    },
  { parola: "NEBBIA",  sillabe: ["NEB",  "BIA"]   },
  { parola: "FIABA",   sillabe: ["FIA",  "BA"]    },
  { parola: "FRASE",   sillabe: ["FRA",  "SE"]    },
  { parola: "NONNA",   sillabe: ["NON",  "NA"]    },
  { parola: "BURRO",   sillabe: ["BUR",  "RO"]    },
  { parola: "SACCO",   sillabe: ["SAC",  "CO"]    },
  { parola: "LUNGO",   sillabe: ["LUN",  "GO"]    },
  { parola: "FUNGO",   sillabe: ["FUN",  "GO"]    },
  { parola: "BORGO",   sillabe: ["BOR",  "GO"]    },
  { parola: "ORZO",    sillabe: ["OR",   "ZO"]    },
  { parola: "COBRA",   sillabe: ["CO",   "BRA"]   },
  { parola: "PANDA",   sillabe: ["PAN",  "DA"]    },
  { parola: "TOMBA",   sillabe: ["TOM",  "BA"]    },
  { parola: "MAPPA",   sillabe: ["MAP",  "PA"]    },

  // ── TRISILLABE (200 parole) ───────────────────────────────────────────────
  { parola: "BAMBINO",   sillabe: ["BAM",  "BI",   "NO"]   },
  { parola: "BAMBINA",   sillabe: ["BAM",  "BI",   "NA"]   },
  { parola: "FARFALLA",  sillabe: ["FAR",  "FAL",  "LA"]   },
  { parola: "CAVALLO",   sillabe: ["CA",   "VAL",  "LO"]   },
  { parola: "BAMBOLA",   sillabe: ["BAM",  "BO",   "LA"]   },
  { parola: "FORMICA",   sillabe: ["FOR",  "MI",   "CA"]   },
  { parola: "UCCELLO",   sillabe: ["UC",   "CEL",  "LO"]   },
  { parola: "CASTELLO",  sillabe: ["CA",   "STEL", "LO"]   },
  { parola: "BOTTONE",   sillabe: ["BOT",  "TO",   "NE"]   },
  { parola: "COLORE",    sillabe: ["CO",   "LO",   "RE"]   },
  { parola: "GELATO",    sillabe: ["GE",   "LA",   "TO"]   },
  { parola: "BANANA",    sillabe: ["BA",   "NA",   "NA"]   },
  { parola: "AMORE",     sillabe: ["A",    "MO",   "RE"]   },
  { parola: "AMICO",     sillabe: ["A",    "MI",   "CO"]   },
  { parola: "NUMERO",    sillabe: ["NU",   "ME",   "RO"]   },
  { parola: "ALBERO",    sillabe: ["AL",   "BE",   "RO"]   },
  { parola: "MINUTO",    sillabe: ["MI",   "NU",   "TO"]   },
  { parola: "CAMPANA",   sillabe: ["CAM",  "PA",   "NA"]   },
  { parola: "TAVOLO",    sillabe: ["TA",   "VO",   "LO"]   },
  { parola: "MATTINA",   sillabe: ["MAT",  "TI",   "NA"]   },
  { parola: "SABATO",    sillabe: ["SA",   "BA",   "TO"]   },
  { parola: "DOMANI",    sillabe: ["DO",   "MA",   "NI"]   },
  { parola: "CUGINO",    sillabe: ["CU",   "GI",   "NO"]   },
  { parola: "NIPOTE",    sillabe: ["NI",   "PO",   "TE"]   },
  { parola: "FRATELLO",  sillabe: ["FRA",  "TEL",  "LO"]   },
  { parola: "SORELLA",   sillabe: ["SO",   "REL",  "LA"]   },
  { parola: "ZUCCHERO",  sillabe: ["ZUC",  "CHE",  "RO"]   },
  { parola: "FORMAGGIO", sillabe: ["FOR", "MAG", "GIO"]  },
  { parola: "SPAGHETTI", sillabe: ["SPA", "GHET", "TI"]   },
  { parola: "PANINO",    sillabe: ["PA",   "NI",   "NO"]   },
  { parola: "BISCOTTO",  sillabe: ["BI",   "SCOT", "TO"]   },
  { parola: "MERENDA",   sillabe: ["ME",   "REN",  "DA"]   },
  { parola: "GIRAFFA",   sillabe: ["GI",   "RAF",  "FA"]   },
  { parola: "LEONE",     sillabe: ["LE",   "O",    "NE"]   },
  { parola: "CAMMELLO",  sillabe: ["CAM",  "MEL",  "LO"]   },
  { parola: "GORILLA",   sillabe: ["GO",   "RIL",  "LA"]   },
  { parola: "CONIGLIO",  sillabe: ["CO",   "NI",   "GLIO"] },
  { parola: "SERPENTE",  sillabe: ["SER",  "PEN",  "TE"]   },
  { parola: "MAIALE",    sillabe: ["MA",   "IA",   "LE"]   },
  { parola: "PECORA",    sillabe: ["PE",   "CO",   "RA"]   },
  { parola: "ASINO",     sillabe: ["A",    "SI",   "NO"]   },
  { parola: "GALLINA",   sillabe: ["GAL",  "LI",   "NA"]   },
  { parola: "PINGUINO",  sillabe: ["PIN",  "GUI",  "NO"]   },
  { parola: "BALENA",    sillabe: ["BA",   "LE",   "NA"]   },
  { parola: "CASTORO",   sillabe: ["CA",   "STO",  "RO"]   },
  { parola: "CAPRIOLO",  sillabe: ["CA",   "PRIO", "LO"]   },
  { parola: "AGOSTO",    sillabe: ["A",    "GO",   "STO"]  },
  { parola: "OTTOBRE",   sillabe: ["OT",   "TO",   "BRE"]  },
  { parola: "NOVEMBRE",  sillabe: ["NO",   "VEM",  "BRE"]  },
  { parola: "DICEMBRE",  sillabe: ["DI",   "CEM",  "BRE"]  },
  { parola: "GENNAIO",   sillabe: ["GEN",  "NA",   "IO"]   },
  { parola: "FEBBRAIO",  sillabe: ["FEB",  "BRA",  "IO"]   },
  { parola: "APRILE",    sillabe: ["A",    "PRI",  "LE"]   },
  { parola: "SETTEMBRE", sillabe: ["SET", "TEM", "BRE"]  },
  { parola: "LUNEDÌ",    sillabe: ["LU",   "NE",   "DÌ"]   },
  { parola: "MARTEDÌ",   sillabe: ["MAR",  "TE",   "DÌ"]   },
  { parola: "GIOVEDÌ",   sillabe: ["GIO",  "VE",   "DÌ"]   },
  { parola: "VENERDÌ",   sillabe: ["VE",   "NER",  "DÌ"]   },
  { parola: "MACCHINA",  sillabe: ["MAC",  "CHI",  "NA"]   },
  { parola: "MOTORE",    sillabe: ["MO",   "TO",   "RE"]   },
  { parola: "OMBRELLO",  sillabe: ["OM",   "BREL", "LO"]   },
  { parola: "CAPPELLO",  sillabe: ["CAP",  "PEL",  "LO"]   },
  { parola: "MAGLIETTA", sillabe: ["MA", "GLIET", "TA"]   },
  { parola: "VESTITO",   sillabe: ["VE",   "STI",  "TO"]   },
  { parola: "STIVALE",   sillabe: ["STI",  "VA",   "LE"]   },
  { parola: "CINTURA",   sillabe: ["CIN",  "TU",   "RA"]   },
  { parola: "CAPPOTTO",  sillabe: ["CAP",  "POT",  "TO"]   },
  { parola: "CALZINO",   sillabe: ["CAL",  "ZI",   "NO"]   },
  { parola: "PIGIAMA",   sillabe: ["PI",   "GIA",  "MA"]   },
  { parola: "COPERTA",   sillabe: ["CO",   "PER",  "TA"]   },
  { parola: "CUSCINO",   sillabe: ["CU",   "SCI",  "NO"]   },
  { parola: "ARMADIO",   sillabe: ["AR",   "MA",   "DIO"]  },
  { parola: "DIVANO",    sillabe: ["DI",   "VA",   "NO"]   },
  { parola: "CUCINA",    sillabe: ["CU",   "CI",   "NA"]   },
  { parola: "CAMERA",    sillabe: ["CA",   "ME",   "RA"]   },
  { parola: "SALOTTO",   sillabe: ["SA",   "LOT",  "TO"]   },
  { parola: "GIARDINO",  sillabe: ["GIAR", "DI",   "NO"]   },
  { parola: "MATITA",    sillabe: ["MA",   "TI",   "TA"]   },
  { parola: "QUADERNO",  sillabe: ["QUA",  "DER",  "NO"]   },
  { parola: "FORBICI",   sillabe: ["FOR",  "BI",   "CI"]   },
  { parola: "PENNELLO",  sillabe: ["PEN",  "NEL",  "LO"]   },
  { parola: "DISEGNO",   sillabe: ["DI",   "SE",   "GNO"]  },
  { parola: "MUSICA",    sillabe: ["MU",   "SI",   "CA"]   },
  { parola: "CHITARRA",  sillabe: ["CHI",  "TAR",  "RA"]   },
  { parola: "VIOLINO",   sillabe: ["VIO",  "LI",   "NO"]   },
  { parola: "CANTANTE",  sillabe: ["CAN",  "TAN",  "TE"]   },
  { parola: "ATTORE",    sillabe: ["AT",   "TO",   "RE"]   },
  { parola: "DOTTORE",   sillabe: ["DOT",  "TO",   "RE"]   },
  { parola: "MAESTRO",   sillabe: ["MA",   "E",    "STRO"] },
  { parola: "MEDICO",    sillabe: ["ME",   "DI",   "CO"]   },
  { parola: "POMPIERE",  sillabe: ["POM",  "PIE",  "RE"]   },
  { parola: "SOLDATO",   sillabe: ["SOL",  "DA",   "TO"]   },
  { parola: "NATURA",    sillabe: ["NA",   "TU",   "RA"]   },
  { parola: "MONTAGNA",  sillabe: ["MON",  "TA",   "GNA"]  },
  { parola: "COLLINA",   sillabe: ["COL",  "LI",   "NA"]   },
  { parola: "FORESTA",   sillabe: ["FO",   "RE",   "STA"]  },
  { parola: "VULCANO",   sillabe: ["VUL",  "CA",   "NO"]   },
  { parola: "PIANETA",   sillabe: ["PIA",  "NE",   "TA"]   },
  { parola: "COMETA",    sillabe: ["CO",   "ME",   "TA"]   },
  { parola: "UNDICI",    sillabe: ["UN",   "DI",   "CI"]   },
  { parola: "DODICI",    sillabe: ["DO",   "DI",   "CI"]   },
  { parola: "TREDICI",   sillabe: ["TRE",  "DI",   "CI"]   },
  { parola: "QUINDICI",  sillabe: ["QUIN", "DI",   "CI"]   },
  { parola: "SEDICI",    sillabe: ["SE",   "DI",   "CI"]   },
  { parola: "INSIEME",   sillabe: ["IN",   "SIE",  "ME"]   },
  { parola: "DAVANTI",   sillabe: ["DA",   "VAN",  "TI"]   },
  { parola: "INTORNO",   sillabe: ["IN",   "TOR",  "NO"]   },
  { parola: "ADESSO",    sillabe: ["A",    "DES",  "SO"]   },
  { parola: "SUBITO",    sillabe: ["SU",   "BI",   "TO"]   },
  { parola: "ANCORA",    sillabe: ["AN",   "CO",   "RA"]   },
  { parola: "GINOCCHIO", sillabe: ["GI", "NOC", "CHIO"] },
  { parola: "ORECCHIO",  sillabe: ["O",    "REC",  "CHIO"] },
  { parola: "SORRISO",   sillabe: ["SOR",  "RI",   "SO"]   },
  { parola: "STOMACO",   sillabe: ["STO",  "MA",   "CO"]   },
  { parola: "CERVELLO",  sillabe: ["CER",  "VEL",  "LO"]   },
  { parola: "CAROTA",    sillabe: ["CA",   "RO",   "TA"]   },
  { parola: "CIPOLLA",   sillabe: ["CI",   "POL",  "LA"]   },
  { parola: "MELONE",    sillabe: ["ME",   "LO",   "NE"]   },
  { parola: "FRAGOLA",   sillabe: ["FRA",  "GO",   "LA"]   },
  { parola: "LAMPONE",   sillabe: ["LAM",  "PO",   "NE"]   },
  { parola: "CILIEGIA",  sillabe: ["CI",   "LIE",  "GIA"]  },
  { parola: "NOCCIOLA",  sillabe: ["NOC",  "CIO",  "LA"]   },
  { parola: "CASTAGNA",  sillabe: ["CA",   "STA",  "GNA"]  },
  { parola: "FAGIOLO",   sillabe: ["FA",   "GIO",  "LO"]   },
  { parola: "PISELLO",   sillabe: ["PI",   "SEL",  "LO"]   },
  { parola: "PADELLA",   sillabe: ["PA",   "DEL",  "LA"]   },
  { parola: "BICCHIERE", sillabe: ["BIC", "CHIE", "RE"]   },
  { parola: "PRINCIPE",  sillabe: ["PRIN", "CI",   "PE"]   },
  { parola: "FANTASMA",  sillabe: ["FAN",  "TA",   "SMA"]  },
  { parola: "GIGANTE",   sillabe: ["GI",   "GAN",  "TE"]   },
  { parola: "RAGAZZO",   sillabe: ["RA",   "GAZ",  "ZO"]   },
  { parola: "RAGAZZA",   sillabe: ["RA",   "GAZ",  "ZA"]   },
  { parola: "GIOVANE",   sillabe: ["GIO",  "VA",   "NE"]   },
  { parola: "AMICA",     sillabe: ["A",    "MI",   "CA"]   },
  { parola: "PALAZZO",   sillabe: ["PA",   "LAZ",  "ZO"]   },
  { parola: "VILLAGGIO", sillabe: ["VIL", "LAG", "GIO"]  },
  { parola: "REGIONE",   sillabe: ["RE",   "GIO",  "NE"]   },
  { parola: "FORTUNA",   sillabe: ["FOR",  "TU",   "NA"]   },
  { parola: "SEGRETO",   sillabe: ["SE",   "GRE",  "TO"]   },
  { parola: "SORPRESA",  sillabe: ["SOR",  "PRE",  "SA"]   },
  { parola: "REGALO",    sillabe: ["RE",   "GA",   "LO"]   },
  { parola: "PARTITA",   sillabe: ["PAR",  "TI",   "TA"]   },
  { parola: "PALLONE",   sillabe: ["PAL",  "LO",   "NE"]   },
  { parola: "CAMPIONE",  sillabe: ["CAM",  "PIO",  "NE"]   },
  { parola: "DELFINO",   sillabe: ["DEL",  "FI",   "NO"]   },
  { parola: "LUMACA",    sillabe: ["LU",   "MA",   "CA"]   },
  { parola: "SENTIERO",  sillabe: ["SEN",  "TIE",  "RO"]   },
  { parola: "CAMMINO",   sillabe: ["CAM",  "MI",   "NO"]   },
  { parola: "CORALLO",   sillabe: ["CO",   "RAL",  "LO"]   },
  { parola: "MEDUSA",    sillabe: ["ME",   "DU",   "SA"]   },
  { parola: "PATTINO",   sillabe: ["PAT",  "TI",   "NO"]   },
  { parola: "NUVOLA",    sillabe: ["NU",   "VO",   "LA"]   },
  { parola: "GRANDINE",  sillabe: ["GRAN", "DI",   "NE"]   },
  { parola: "FOLGORE",   sillabe: ["FOL",  "GO",   "RE"]   },
  { parola: "CICLONE",   sillabe: ["CI",   "CLO",  "NE"]   },
  { parola: "STAGIONE",  sillabe: ["STA",  "GIO",  "NE"]   },
  { parola: "INVERNO",   sillabe: ["IN",   "VER",  "NO"]   },
  { parola: "AUTUNNO",   sillabe: ["AU",   "TUN",  "NO"]   },
  { parola: "ESTATE",    sillabe: ["E",    "STA",  "TE"]   },
  { parola: "TEMPESTA",  sillabe: ["TEM",  "PE",   "STA"]  },
  { parola: "FULMINE",   sillabe: ["FUL",  "MI",   "NE"]   },
  { parola: "SILENZIO",  sillabe: ["SI",   "LEN",  "ZIO"]  },
  { parola: "RUMORE",    sillabe: ["RU",   "MO",   "RE"]   },
  { parola: "PROFUMO",   sillabe: ["PRO",  "FU",   "MO"]   },
  { parola: "ODORE",     sillabe: ["O",    "DO",   "RE"]   },
  { parola: "SAPORE",    sillabe: ["SA",   "PO",   "RE"]   },
  { parola: "CALORE",    sillabe: ["CA",   "LO",   "RE"]   },
  { parola: "DOLCIUMI",  sillabe: ["DOL",  "CIU",  "MI"]   },
  { parola: "RICOTTA",   sillabe: ["RI",   "COT",  "TA"]   },
  { parola: "POLENTA",   sillabe: ["PO",   "LEN",  "TA"]   },
  { parola: "MINESTRA",  sillabe: ["MI",   "NE",   "STRA"] },
  { parola: "GAMBERO",   sillabe: ["GAM",  "BE",   "RO"]   },
  { parola: "LIBERTÀ",   sillabe: ["LI",   "BER",  "TÀ"]   },
  { parola: "VERITÀ",    sillabe: ["VE",   "RI",   "TÀ"]   },
  { parola: "SILABA",    sillabe: ["SIL",  "LA",   "BA"]   },
  { parola: "PAROLA",    sillabe: ["PA",   "RO",   "LA"]   },
  { parola: "PAGINA",    sillabe: ["PA",   "GI",   "NA"]   },
  { parola: "PERSONA",   sillabe: ["PER",  "SO",   "NA"]   },
  { parola: "GOVERNO",   sillabe: ["GO",   "VER",  "NO"]   },
  { parola: "POPOLO",    sillabe: ["PO",   "PO",   "LO"]   },
  { parola: "PICCOLO",   sillabe: ["PIC",  "CO",   "LO"]   },
  { parola: "FACILE",    sillabe: ["FA",   "CI",   "LE"]   },
  { parola: "MAGICO",    sillabe: ["MA",   "GI",   "CO"]   },
  { parola: "COMICO",    sillabe: ["CO",   "MI",   "CO"]   },
  { parola: "LIBERO",    sillabe: ["LI",   "BE",   "RO"]   },
  { parola: "SICURO",    sillabe: ["SI",   "CU",   "RO"]   },
  { parola: "VELOCE",    sillabe: ["VE",   "LO",   "CE"]   },
  { parola: "VICINO",    sillabe: ["VI",   "CI",   "NO"]   },
  { parola: "LONTANO",   sillabe: ["LON",  "TA",   "NO"]   },
  { parola: "INDIETRO",  sillabe: ["IN",   "DIE",  "TRO"]  },
  { parola: "AVANTI",    sillabe: ["A",    "VAN",  "TI"]   },
  { parola: "RONDINE",   sillabe: ["RON",  "DI",   "NE"]   },
  { parola: "POLIZIA",   sillabe: ["PO",   "LI",   "ZIA"]  },
  { parola: "DENTISTA",  sillabe: ["DEN",  "TI",   "STA"]  },
  { parola: "PILOTA",    sillabe: ["PI",   "LO",   "TA"]   },

  // ── QUADRISILLABE (150 parole) ────────────────────────────────────────────
  { parola: "TARTARUGA",    sillabe: ["TAR",  "TA",   "RU",   "GA"]   },
  { parola: "ELEFANTE",     sillabe: ["E",    "LE",   "FAN",  "TE"]   },
  { parola: "PAPPAGALLO",   sillabe: ["PAP",  "PA",   "GAL",  "LO"]   },
  { parola: "COCCODRILLO",  sillabe: ["COC",  "CO",   "DRIL", "LO"]   },
  { parola: "CIOCCOLATO",   sillabe: ["CIOC", "CO",   "LA",   "TO"]   },
  { parola: "POMODORO",     sillabe: ["PO",   "MO",   "DO",   "RO"]   },
  { parola: "ANIMALE",      sillabe: ["A",    "NI",   "MA",   "LE"]   },
  { parola: "BIBLIOTECA",   sillabe: ["BI",   "BLIO", "TE",   "CA"]   },
  { parola: "OSPEDALE",     sillabe: ["O",    "SPE",  "DA",   "LE"]   },
  { parola: "TELEFONO",     sillabe: ["TE",   "LE",   "FO",   "NO"]   },
  { parola: "BICICLETTA",   sillabe: ["BI",   "CI",   "CLET", "TA"]   },
  { parola: "MOTORINO",     sillabe: ["MO",   "TO",   "RI",   "NO"]   },
  { parola: "OMBRELLONE",   sillabe: ["OM",   "BREL", "LO",   "NE"]   },
  { parola: "OROLOGIO",     sillabe: ["O",    "RO",   "LO",   "GIO"]  },
  { parola: "PERSONAGGIO",  sillabe: ["PER",  "SO",   "NAG",  "GIO"]  },
  { parola: "AVVENTURA",    sillabe: ["AV",   "VEN",  "TU",   "RA"]   },
  { parola: "FANTASTICO",   sillabe: ["FAN",  "TA",   "STI",  "CO"]   },
  { parola: "MAGNIFICO",    sillabe: ["MA",   "GNI",  "FI",   "CO"]   },
  { parola: "TERRIBILE",    sillabe: ["TER",  "RI",   "BI",   "LE"]   },
  { parola: "MERAVIGLIA",   sillabe: ["ME",   "RA",   "VI",   "GLIA"] },
  { parola: "DIVERTENTE",   sillabe: ["DI",   "VER",  "TEN",  "TE"]   },
  { parola: "SILENZIOSO",   sillabe: ["SI",   "LEN",  "ZIO",  "SO"]   },
  { parola: "RUMOROSO",     sillabe: ["RU",   "MO",   "RO",   "SO"]   },
  { parola: "GENEROSO",     sillabe: ["GE",   "NE",   "RO",   "SO"]   },
  { parola: "CORAGGIOSO",   sillabe: ["CO",   "RAG",  "GIO",  "SO"]   },
  { parola: "MISTERIOSO",   sillabe: ["MI",   "STE",  "RIO",  "SO"]   },
  { parola: "TALENTUOSO",  sillabe: ["TA",   "LEN",  "TUO",  "SO"]   },
  { parola: "DIFFICILE",    sillabe: ["DIF",  "FI",   "CI",   "LE"]   },
  { parola: "POSSIBILE",    sillabe: ["POS",  "SI",   "BI",   "LE"]   },
  { parola: "IMPORTANTE",   sillabe: ["IM",   "POR",  "TAN",  "TE"]   },
  { parola: "GIOCATTOLO",   sillabe: ["GIO",  "CAT",  "TO",   "LO"]   },
  { parola: "PLASTILINA",   sillabe: ["PLA",  "STI",  "LI",   "NA"]   },
  { parola: "COSTRUZIONE",  sillabe: ["CO",   "STRU", "ZIO",  "NE"]   },
  { parola: "PORCOSPINO",  sillabe: ["POR",  "CO",   "SPI",  "NO"]   },
  { parola: "VIDEOGIOCO",   sillabe: ["VI",   "DEO",  "GIO",  "CO"]   },
  { parola: "COCCINELLA",   sillabe: ["COC",  "CI",   "NEL",  "LA"]   },
  { parola: "LUCERTOLA",    sillabe: ["LU",   "CER",  "TO",   "LA"]   },
  { parola: "SCOIATTOLO",   sillabe: ["SCO",  "IAT",  "TO",   "LO"]   },
  { parola: "IPPOCAMPO",    sillabe: ["IP",   "PO",   "CAM",  "PO"]   },
  { parola: "LEOPARDO",     sillabe: ["LE",   "O",    "PAR",  "DO"]   },
  { parola: "GIRASOLE",     sillabe: ["GI",   "RA",   "SO",   "LE"]   },
  { parola: "DINOSAURO",    sillabe: ["DI",   "NO",   "SAU",  "RO"]   },
  { parola: "ALBICOCCA",    sillabe: ["AL",   "BI",   "COC",  "CA"]   },
  { parola: "CARAMELLA",    sillabe: ["CA",   "RA",   "MEL",  "LA"]   },
  { parola: "LIMONATA",     sillabe: ["LI",   "MO",   "NA",   "TA"]   },
  { parola: "ARANCIATA",    sillabe: ["A",    "RAN",  "CIA",  "TA"]   },
  { parola: "CIOCCOLATA",   sillabe: ["CIOC", "CO",   "LA",   "TA"]   },
  { parola: "INSALATA",     sillabe: ["IN",   "SA",   "LA",   "TA"]   },
  { parola: "MOZZARELLA",   sillabe: ["MOZ",  "ZA",   "REL",  "LA"]   },
  { parola: "PROVOLONE",    sillabe: ["PRO",  "VO",   "LO",   "NE"]   },
  { parola: "PECORINO",     sillabe: ["PE",   "CO",   "RI",   "NO"]   },
  { parola: "PARMIGIANO",   sillabe: ["PAR",  "MI",   "GIA",  "NO"]   },
  { parola: "AMARETTO",     sillabe: ["A",    "MA",   "RET",  "TO"]   },
  { parola: "TIRAMISÙ",     sillabe: ["TI",   "RA",   "MI",   "SÙ"]   },
  { parola: "PANETTONE",    sillabe: ["PA",   "NET",  "TO",   "NE"]   },
  { parola: "TAGLIATELLE",  sillabe: ["TA",   "GLIA", "TEL",  "LE"]   },
  { parola: "MACCHERONI",   sillabe: ["MAC",  "CHE",  "RO",   "NI"]   },
  { parola: "RIGATONI",     sillabe: ["RI",   "GA",   "TO",   "NI"]   },
  { parola: "CARBONARA",    sillabe: ["CAR",  "BO",   "NA",   "RA"]   },
  { parola: "BOLOGNESE",    sillabe: ["BO",   "LO",   "GNE",  "SE"]   },
  { parola: "TERREMOTO",    sillabe: ["TER",  "RE",   "MO",   "TO"]   },
  { parola: "PANORAMA",     sillabe: ["PA",   "NO",   "RA",   "MA"]   },
  { parola: "ORIZZONTE",    sillabe: ["O",    "RIZ",  "ZON",  "TE"]   },
  { parola: "CAMPANILE",    sillabe: ["CAM",  "PA",   "NI",   "LE"]   },
  { parola: "ATMOSFERA",    sillabe: ["AT",   "MOS",  "FE",   "RA"]   },
  { parola: "TELESCOPIO",   sillabe: ["TE",   "LE",   "SCO",  "PIO"]  },
  { parola: "SATELLITE",    sillabe: ["SA",   "TEL",  "LI",   "TE"]   },
  { parola: "ASTEROIDE",    sillabe: ["A",    "STE",  "ROI",  "DE"]   },
  { parola: "PLANETARIO",   sillabe: ["PLA",  "NE",   "TA",   "RIO"]  },
  { parola: "OCEANO",       sillabe: ["O",    "CE",   "A",    "NO"]   },
  { parola: "ITALIANO",     sillabe: ["I",    "TA",   "LIA",  "NO"]   },
  { parola: "NAZIONALE",    sillabe: ["NA",   "ZIO",  "NA",   "LE"]   },
  { parola: "TRADIZIONE",   sillabe: ["TRA",  "DI",   "ZIO",  "NE"]   },
  { parola: "PRODUZIONE",   sillabe: ["PRO",  "DU",   "ZIO",  "NE"]   },
  { parola: "SOLUZIONE",    sillabe: ["SO",   "LU",   "ZIO",  "NE"]   },
  { parola: "COLLEZIONE",   sillabe: ["COL",  "LE",   "ZIO",  "NE"]   },
  { parola: "POSIZIONE",    sillabe: ["PO",   "SI",   "ZIO",  "NE"]   },
  { parola: "ATTENZIONE",   sillabe: ["AT",   "TEN",  "ZIO",  "NE"]   },
  { parola: "DIREZIONE",    sillabe: ["DI",   "RE",   "ZIO",  "NE"]   },
  { parola: "SITUAZIONE",   sillabe: ["SI",   "TUA",  "ZIO",  "NE"]   },
  { parola: "DIRETTORE",    sillabe: ["DI",   "RET",  "TO",   "RE"]   },
  { parola: "PROFESSORE",   sillabe: ["PRO",  "FES",  "SO",   "RE"]   },
  { parola: "INFERMIERE",   sillabe: ["IN",   "FER",  "MIE",  "RE"]   },
  { parola: "CAMERIERE",    sillabe: ["CA",   "ME",   "RIE",  "RE"]   },
  { parola: "GIARDINIERE",  sillabe: ["GIAR", "DI",   "NIE",  "RE"]   },
  { parola: "ASTRONAUTA",   sillabe: ["A",    "STRO", "NAU",  "TA"]   },
  { parola: "CAPITANO",     sillabe: ["CA",   "PI",   "TA",   "NO"]   },
  { parola: "INGEGNERE",    sillabe: ["IN",   "GE",   "GNE",  "RE"]   },
  { parola: "AVVOCATO",     sillabe: ["AV",   "VO",   "CA",   "TO"]   },
  { parola: "ARCHITETTO",   sillabe: ["AR",   "CHI",  "TET",  "TO"]   },
  { parola: "FARMACISTA",   sillabe: ["FAR",  "MA",   "CI",   "STA"]  },
  { parola: "PSICOLOGO",    sillabe: ["PSI",  "CO",   "LO",   "GO"]   },
  { parola: "CAROSELLO",    sillabe: ["CA",   "RO",   "SEL",  "LO"]   },
  { parola: "BALLERINA",    sillabe: ["BAL",  "LE",   "RI",   "NA"]   },
  { parola: "CALCIATORE",   sillabe: ["CAL",  "CIA",  "TO",   "RE"]   },
  { parola: "CAMPIONATO",   sillabe: ["CAM",  "PIO",  "NA",   "TO"]   },
  { parola: "PORTAFOGLIO",  sillabe: ["POR",  "TA",   "FO",   "GLIO"] },
  { parola: "CALENDARIO",   sillabe: ["CA",   "LEN",  "DA",   "RIO"]  },
  { parola: "MINESTRONE",   sillabe: ["MI",   "NE",   "STRO", "NE"]   },
  { parola: "CALAMARO",     sillabe: ["CA",   "LA",   "MA",   "RO"]   },
  { parola: "MAMMIFERO",    sillabe: ["MAM",  "MI",   "FE",   "RO"]   },
  { parola: "PRIMAVERA",    sillabe: ["PRI",  "MA",   "VE",   "RA"]   },
  { parola: "TEMPORALE",    sillabe: ["TEM",  "PO",   "RA",   "LE"]   },
  { parola: "CARNEVALE",    sillabe: ["CAR",  "NE",   "VA",   "LE"]   },
  { parola: "FELICITÀ",     sillabe: ["FE",   "LI",   "CI",   "TÀ"]   },
  { parola: "NECESSARIO",   sillabe: ["NE",   "CES",  "SA",   "RIO"]  },
  { parola: "SPECIALMENTE", sillabe: ["SPE", "CIAL", "MEN", "TE"]   },
  { parola: "IMPAZIENTE",   sillabe: ["IM",   "PA",   "ZIEN", "TE"]   },
  { parola: "SPAVENTATO",   sillabe: ["SPA",  "VEN",  "TA",   "TO"]   },
  { parola: "SORPRENDENTE", sillabe: ["SOR", "PREN", "DEN", "TE"]   },
  { parola: "CHIARAMENTE",  sillabe: ["CHIA", "RA",   "MEN",  "TE"]   },
  { parola: "RISPETTOSO",   sillabe: ["RI",   "SPET", "TO",   "SO"]   },
  { parola: "COLORATO",     sillabe: ["CO",   "LO",   "RA",   "TO"]   },
  { parola: "PROFUMATO",    sillabe: ["PRO",  "FU",   "MA",   "TO"]   },
  { parola: "RIDICOLO",     sillabe: ["RI",   "DI",   "CO",   "LO"]   },
  { parola: "ATTIVITÀ",     sillabe: ["AT",   "TI",   "VI",   "TÀ"]   },
  { parola: "DIFFICOLTÀ",   sillabe: ["DIF",  "FI",   "COL",  "TÀ"]   },
  { parola: "CURIOSITÀ",    sillabe: ["CU",   "RIO",  "SI",   "TÀ"]   },
  { parola: "ALLEGRIA",     sillabe: ["AL",   "LE",   "GRI",  "A"]    },
  { parola: "NOSTALGIA",    sillabe: ["NO",   "STAL", "GI",   "A"]    },
  { parola: "FANTASIA",     sillabe: ["FAN",  "TA",   "SI",   "A"]    },
  { parola: "MELODIA",      sillabe: ["ME",   "LO",   "DI",   "A"]    },
  { parola: "SINFONIA",     sillabe: ["SIN",  "FO",   "NI",   "A"]    },
  { parola: "POESIA",       sillabe: ["PO",   "E",    "SI",   "A"]    },
  { parola: "ENERGIA",      sillabe: ["E",    "NER",  "GI",   "A"]    },
  { parola: "REPUBBLICA",   sillabe: ["RE",   "PUB",  "BLI",  "CA"]   },
  { parola: "DEMOCRAZIA",   sillabe: ["DE",   "MO",   "CRA",  "ZIA"]  },
  { parola: "UNICORNO",     sillabe: ["U",    "NI",   "COR",  "NO"]   },
  { parola: "DRAGONESSA",   sillabe: ["DRA",  "GO",   "NES",  "SA"]   },
  { parola: "CAVALIERE",    sillabe: ["CA",   "VA",   "LIE",  "RE"]   },
  { parola: "PRINCIPESSA",  sillabe: ["PRIN", "CI",   "PES",  "SA"]   },
  { parola: "OSSOBUCO",     sillabe: ["OS",   "SO",   "BU",   "CO"]   },
  { parola: "PASTICCERIA",  sillabe: ["PA",   "STIC", "CE",   "RIA"]  },
  { parola: "TRATTORIA",    sillabe: ["TRAT", "TO",   "RI",   "A"]    },
  { parola: "PARADISO",     sillabe: ["PA",   "RA",   "DI",   "SO"]   },
  { parola: "BINOCOLO",     sillabe: ["BI",   "NOC",  "CO",   "LO"]   },
  { parola: "CATALOGO",     sillabe: ["CA",   "TA",   "LO",   "GO"]   },
  { parola: "SEMAFORO",     sillabe: ["SE",   "MA",   "FO",   "RO"]   },
  { parola: "GALASSIA",     sillabe: ["GA",   "LAS",  "SI",   "A"]    },
  { parola: "GONDOLIERE",   sillabe: ["GON",  "DO",   "LIE",  "RE"]   },
  { parola: "CITTADINO",    sillabe: ["CIT",  "TA",   "DI",   "NO"]   },
  { parola: "CONTADINO",    sillabe: ["CON",  "TA",   "DI",   "NO"]   },
  { parola: "FALEGNAME",    sillabe: ["FA",   "LE",   "GNA",  "ME"]   },
  { parola: "PATRIMONIO",   sillabe: ["PA",   "TRI",  "MO",   "NIO"]  },
];
