const parole = [
{ parola: "APE",    sillabe: ["A",   "PE"]    },
{ parola: "AGO",    sillabe: ["A",   "GO"]    },
{ parola: "ALA",    sillabe: ["A",   "LA"]    },
{ parola: "BACO",    sillabe: ["BA",   "CO"]    },
{ parola: "BARA",    sillabe: ["BA",   "RA"]    },
{ parola: "BASE",    sillabe: ["BA",   "SE"]    },
{ parola: "BEVO",    sillabe: ["BE",   "VO"]    },
{ parola: "BENE",    sillabe: ["BE",   "NE"]    },
{ parola: "BICI",    sillabe: ["BI",   "CI"]    },
{ parola: "BIGA",    sillabe: ["BI",   "GA"]    },
{ parola: "BINO",    sillabe: ["BI",   "NO"]    },
{ parola: "BOGA",    sillabe: ["BO",   "GA"]    },
{ parola: "BORA",    sillabe: ["BO",   "RA"]    },
{ parola: "BUCO",    sillabe: ["BU",   "CO"]    },
{ parola: "BOVE",    sillabe: ["BO",   "VE"]    },
{ parola: "CADI",    sillabe: ["CA",   "DI"]    },
{ parola: "CADO",    sillabe: ["CA",   "DO"]    },
{ parola: "CANE",    sillabe: ["CA",   "NE"]    },
{ parola: "CAPO",    sillabe: ["CA",   "PO"]    },
{ parola: "CASA",    sillabe: ["CA",   "SA"]    },
{ parola: "CAVA",    sillabe: ["CA",   "VA"]    },
{ parola: "CENA",    sillabe: ["CE",   "NA"]    },
{ parola: "CERA",    sillabe: ["CE",   "RA"]    },
{ parola: "CETO",    sillabe: ["CE",   "TO"]    },
{ parola: "CIBO",    sillabe: ["CI",   "BO"]    },
{ parola: "CIMA",    sillabe: ["CI",   "MA"]    },
{ parola: "CINA",    sillabe: ["CI",   "NA"]    },
{ parola: "CITO",    sillabe: ["CI",   "TO"]    },
{ parola: "CODA",    sillabe: ["CO",   "DA"]    },
{ parola: "COMA",    sillabe: ["CO",   "MA"]    },
{ parola: "CONO",    sillabe: ["CO",   "NO"]    },
{ parola: "CORA",    sillabe: ["CO",   "RA"]    },
{ parola: "COSA",    sillabe: ["CO",   "SA"]    },
{ parola: "COVO",    sillabe: ["CO",   "VO"]    },
{ parola: "CURA",    sillabe: ["CU",   "RA"]    },
{ parola: "CUTE",    sillabe: ["CU",   "TE"]    },
{ parola: "DADI",    sillabe: ["DA",   "DI"]    },
{ parola: "DADO",    sillabe: ["DA",   "DO"]    },
{ parola: "DAMA",    sillabe: ["DA",   "MA"]    },
{ parola: "DITO",    sillabe: ["DI",   "TO"]    },
{ parola: "DIVA",    sillabe: ["DI",   "VA"]    },
{ parola: "DIVO",    sillabe: ["DI",   "VO"]    },
{ parola: "DOGE",    sillabe: ["DO",   "GE"]    },
{ parola: "DOGA",    sillabe: ["DO",   "GA"]    },
{ parola: "DOMO",    sillabe: ["DO",   "MO"]    },
{ parola: "DONO",    sillabe: ["DO",   "NO"]    },
{ parola: "DOPO",    sillabe: ["DO",   "PO"]    },
{ parola: "DOSE",    sillabe: ["DO",   "SE"]    },
{ parola: "DUCA",    sillabe: ["DU",   "CA"]    },
{ parola: "DUNA",    sillabe: ["DU",   "NA"]    },
{ parola: "DURO",    sillabe: ["DU",   "RO"]    },
{ parola: "FAME",    sillabe: ["FA",   "ME"]    },
{ parola: "FARO",    sillabe: ["FA",   "RO"]    },
{ parola: "FASE",    sillabe: ["FA",   "SE"]    },
{ parola: "FATO",    sillabe: ["FA",   "TO"]    },
{ parola: "FEDE",    sillabe: ["FE",   "DE"]    },
{ parola: "FICO",    sillabe: ["FI",   "CO"]    },
{ parola: "FIDO",    sillabe: ["FI",   "DO"]    },
{ parola: "FILO",    sillabe: ["FI",   "LO"]    },
{ parola: "FINE",    sillabe: ["FI",   "NE"]    },
{ parola: "FINO",    sillabe: ["FI",   "NO"]    },
{ parola: "FOGA",    sillabe: ["FO",   "GA"]    },
{ parola: "FOTO",    sillabe: ["FO",   "TO"]    },
{ parola: "FORO",    sillabe: ["FO",   "RO"]    },
{ parola: "FUNE",    sillabe: ["FU",   "NE"]    },
{ parola: "FUMO",    sillabe: ["FU",   "MO"]    },
{ parola: "GALA",    sillabe: ["GA",   "LA"]    },
{ parola: "GARA",    sillabe: ["GA",   "RA"]    },
{ parola: "GARA",    sillabe: ["GA",   "RA"]    },
{ parola: "GECO",    sillabe: ["GE",   "CO"]    },
{ parola: "GELO",    sillabe: ["GE",   "LO"]    },
{ parola: "GEMA",    sillabe: ["GE",   "MA"]    },
{ parola: "GINO",    sillabe: ["GI",   "NO"]    },
{ parola: "GIRO",    sillabe: ["GI",   "RO"]    },
{ parola: "GITA",    sillabe: ["GI",   "TA"]    },
{ parola: "GOGA",    sillabe: ["GO",   "GA"]    },
{ parola: "GOLA",    sillabe: ["GO",   "LA"]    },
{ parola: "GOMA",    sillabe: ["GO",   "MA"]    },
{ parola: "GUFO",    sillabe: ["GU",   "FO"]    },
{ parola: "IVA",    sillabe: ["I",   "VA"]    },
{ parola: "IRA",    sillabe: ["I",   "RA"]    },
{ parola: "LAMA",    sillabe: ["LA",   "MA"]    },
{ parola: "LATO",    sillabe: ["LA",   "TO"]    },
{ parola: "LAVA",    sillabe: ["LA",   "VA"]    },
{ parola: "LEGO",    sillabe: ["LE",   "GO"]    },
{ parola: "LENA",    sillabe: ["LE",   "NA"]    },
{ parola: "LINO",    sillabe: ["LI",   "NO"]    },
{ parola: "LIRA",    sillabe: ["LI",   "RA"]    },
{ parola: "LISO",    sillabe: ["LI",   "SO"]    },
{ parola: "LITO",    sillabe: ["LI",   "TO"]    },
{ parola: "LOBO",    sillabe: ["LO",   "BO"]    },
{ parola: "LOCO",    sillabe: ["LO",   "CO"]    },
{ parola: "LODE",    sillabe: ["LO",   "DE"]    },
{ parola: "LOTO",    sillabe: ["LO",   "TO"]    },
{ parola: "LUCE",    sillabe: ["LU",   "CE"]    },
{ parola: "LUMA",    sillabe: ["LU",   "MA"]    },
{ parola: "LUPO",    sillabe: ["LU",   "PO"]    },
{ parola: "MAGO",    sillabe: ["MA",   "GO"]    },
{ parola: "MANO",    sillabe: ["MA",   "NO"]    },
{ parola: "MARE",    sillabe: ["MA",   "RE"]    },
{ parola: "MELA",    sillabe: ["ME",   "LA"]    },
{ parola: "MENO",    sillabe: ["ME",   "NO"]    },
{ parola: "META",    sillabe: ["ME",   "TA"]    },
{ parola: "MICA",    sillabe: ["MI",   "CA"]    },
{ parola: "MIMO",    sillabe: ["MI",   "MO"]    },
{ parola: "MINA",    sillabe: ["MI",   "NA"]    },
{ parola: "MIRA",    sillabe: ["MI",   "RA"]    },
{ parola: "MITO",    sillabe: ["MI",   "TO"]    },
{ parola: "MODA",    sillabe: ["MO",   "DA"]    },
{ parola: "MOLO",    sillabe: ["MO",   "LO"]    },
{ parola: "MORA",    sillabe: ["MO",   "RA"]    },
{ parola: "MORO",    sillabe: ["MO",   "RO"]    },
{ parola: "MUTO",    sillabe: ["MU",   "TO"]    },
{ parola: "MURA",    sillabe: ["MU",   "RA"]    },
{ parola: "NASO",    sillabe: ["NA",   "SO"]    },
{ parola: "NATO",    sillabe: ["NA",   "TO"]    },
{ parola: "NAVE",    sillabe: ["NA",   "VE"]    },
{ parola: "NERO",    sillabe: ["NE",   "RO"]    },
{ parola: "NIDO",    sillabe: ["NI",   "DO"]    },
{ parola: "NOTO",    sillabe: ["NO",   "TO"]    },
{ parola: "NOVE",    sillabe: ["NO",   "VE"]    },
{ parola: "NUDO",    sillabe: ["NU",   "DO"]    },
{ parola: "PAGA",    sillabe: ["PA",   "GA"]    },
{ parola: "PALO",    sillabe: ["PA",   "LO"]    },
{ parola: "PANE",    sillabe: ["PA",   "NE"]    },
{ parola: "PAPA",    sillabe: ["PA",   "PA"]    },
{ parola: "PARA",    sillabe: ["PA",   "RA"]    },
{ parola: "PERA",    sillabe: ["PE",   "RA"]    },
{ parola: "PELO",    sillabe: ["PE",   "LO"]    },
{ parola: "PESO",    sillabe: ["PE",   "SO"]    },
{ parola: "PINO",    sillabe: ["PI",   "NO"]    },
{ parola: "PIPA",    sillabe: ["PI",   "PA"]    },
{ parola: "PISA",    sillabe: ["PI",   "SA"]    },
{ parola: "POCO",    sillabe: ["PO",   "CO"]    },
{ parola: "POLO",    sillabe: ["PO",   "LO"]    },
{ parola: "POMO",    sillabe: ["PO",   "MO"]    },
{ parola: "POSA",    sillabe: ["PO",   "SA"]    },
{ parola: "PUMA",    sillabe: ["PU",   "MA"]    },
{ parola: "RADA",    sillabe: ["RA",   "DA"]    },
{ parola: "RADO",    sillabe: ["RA",   "DO"]    },
{ parola: "RAME",    sillabe: ["RA",   "ME"]    },
{ parola: "RANA",    sillabe: ["RA",   "NA"]    },
{ parola: "RAPA",    sillabe: ["RA",   "PA"]    },
{ parola: "RASA",    sillabe: ["RA",   "SA"]    },
{ parola: "RASO",    sillabe: ["RA",   "SO"]    },
{ parola: "RETE",    sillabe: ["RE",   "TE"]    },
{ parola: "REMO",    sillabe: ["RE",   "MO"]    },
{ parola: "RISO",    sillabe: ["RI",   "SO"]    },
{ parola: "RIVA",    sillabe: ["RI",   "VA"]    },
{ parola: "ABITO",    sillabe: ["A",   "BI",   "TO"]    },
{ parola: "ACETO",    sillabe: ["A",   "CE",   "TO"]    },
{ parola: "AGATA",    sillabe: ["A",   "GA",   "TA"]    },
{ parola: "AGONE",    sillabe: ["A",   "GO",   "NE"]    },
{ parola: "AMACA",    sillabe: ["A",   "MA",   "CA"]    },
{ parola: "AMICO",    sillabe: ["A",   "MI",   "CO"]    },
{ parola: "AMORE",    sillabe: ["A",   "MO",   "RE"]    },
{ parola: "ANICE",    sillabe: ["A",   "NI",   "CE"]    },
{ parola: "ANODO",    sillabe: ["A",   "NO",   "DO"]    },
{ parola: "ASILO",    sillabe: ["A",   "SI",   "LO"]    },
{ parola: "ATOMO",    sillabe: ["A",   "TO",   "MO"]    },
{ parola: "AVANA",    sillabe: ["A",   "VA",   "NA"]    },
{ parola: "AVERE",    sillabe: ["A",   "VE",   "RE"]    },
{ parola: "ASINO",    sillabe: ["A",   "SI",   "NO"]    },
{ parola: "BALENA",    sillabe: ["BA",   "LE",   "NA"]    },
{ parola: "BANANO",    sillabe: ["BA",   "NA",   "NO"]    },
{ parola: "BARILE",    sillabe: ["BA",   "RI",   "LE"]    },
{ parola: "BAVOSA",    sillabe: ["BA",   "VO",   "SA"]    },
{ parola: "BIBITA",    sillabe: ["BI",   "BI",   "TA"]    },
{ parola: "BINARI",    sillabe: ["BI",   "NA",   "RI"]    },
{ parola: "BIPEDE",    sillabe: ["BI",   "PE",   "DE"]    },
{ parola: "BOBINA",    sillabe: ["BO",   "BI",   "NA"]    },
{ parola: "BUFALO",    sillabe: ["BU",   "FA",   "LO"]    },
{ parola: "CABINA",    sillabe: ["CA",   "BI",   "NA"]    },
{ parola: "CADICE",    sillabe: ["CA",   "DI",   "CE"]    },
{ parola: "CADUTA",    sillabe: ["CA",   "DU",   "TA"]    },
{ parola: "CALICE",    sillabe: ["CA",   "LI",   "CE"]    },
{ parola: "CALURA",    sillabe: ["CA",   "LU",   "RA"]    },
{ parola: "CAMICE",    sillabe: ["CA",   "MI",   "CE"]    },
{ parola: "CAMINO",    sillabe: ["CA",   "MI",   "NO"]    },
{ parola: "CATENA",    sillabe: ["CA",   "TE",   "NA"]    },
{ parola: "CAPIRE",    sillabe: ["CA",   "PI",   "RE"]    },
{ parola: "CARINA",    sillabe: ["CA",   "RI",   "NA"]    },
{ parola: "CARINO",    sillabe: ["CA",   "RI",   "NO"]    },
{ parola: "CAROTA",    sillabe: ["CA",   "RO",   "TA"]    },
{ parola: "CASINA",    sillabe: ["CA",   "SI",   "NA"]    },
{ parola: "CAVOLO",    sillabe: ["CA",   "VO",   "LO"]    },
{ parola: "CECITÀ",    sillabe: ["CE",   "CI",   "TÀ"]    },
{ parola: "CENERE",    sillabe: ["CE",   "NE",   "RE"]    },
{ parola: "CERUME",    sillabe: ["CE",   "RU",   "ME"]    },
{ parola: "CINESE",    sillabe: ["CI",   "NE",   "SE"]    },
{ parola: "CIMICE",    sillabe: ["CI",   "MI",   "CE"]    },
{ parola: "CINEMA",    sillabe: ["CI",   "NE",   "MA"]    },
{ parola: "CITARE",    sillabe: ["CI",   "TA",   "RE"]    },
{ parola: "COFANO",    sillabe: ["CO",   "FA",   "NO"]    },
{ parola: "COLORE",    sillabe: ["CO",   "LO",   "RE"]    },
{ parola: "COMETA",    sillabe: ["CO",   "ME",   "TA"]    },
{ parola: "COMODO",    sillabe: ["CO",   "MO",   "DO"]    },
{ parola: "CORONA",    sillabe: ["CO",   "RO",   "NA"]    },
{ parola: "CUGINO",    sillabe: ["CU",   "GI",   "NO"]    },
{ parola: "CUPOLA",    sillabe: ["CU",   "PO",   "LA"]    },
{ parola: "CURARE",    sillabe: ["CU",   "RA",   "RE"]    },
{ parola: "DANARO",    sillabe: ["DA",   "NA",   "RO"]    },
{ parola: "DELUSO",    sillabe: ["DE",   "LU",   "SO"]    },
{ parola: "DENARO",    sillabe: ["DE",   "NA",   "RO"]    },
{ parola: "DEPONE",    sillabe: ["DE",   "PO",   "NE"]    },
{ parola: "DERIVA",    sillabe: ["DE",   "RI",   "VA"]    },
{ parola: "DIVANO",    sillabe: ["DI",   "VA",   "NO"]    },
{ parola: "DOVERE",    sillabe: ["DO",   "VE",   "RE"]    },
{ parola: "DOMANI",    sillabe: ["DO",   "MA",   "NI"]    },
{ parola: "DOSARE",    sillabe: ["DO",   "SA",   "RE"]    },
{ parola: "DUCATO",    sillabe: ["DU",   "CA",   "TO"]    },
{ parola: "DURATA",    sillabe: ["DU",   "RA",   "TA"]    },
{ parola: "EPOCA",    sillabe: ["E",   "PO",   "CA"]    },
{ parola: "EREDE",    sillabe: ["E",   "RE",   "DE"]    },
{ parola: "ESAME",    sillabe: ["E",   "SA",   "ME"]    },
{ parola: "ESITO",    sillabe: ["E",   "SI",   "TO"]    },
{ parola: "EVASO",    sillabe: ["E",   "VA",   "SO"]    },
{ parola: "FAGONE",    sillabe: ["FA",   "GO",   "NE"]    },
{ parola: "FASANO",    sillabe: ["FA",   "SA",   "NO"]    },
{ parola: "FATINA",    sillabe: ["FA",   "TI",   "NA"]    },
{ parola: "FATICA",    sillabe: ["FA",   "TI",   "CA"]    },
{ parola: "FAVOLA",    sillabe: ["FA",   "VO",   "LA"]    },
{ parola: "FERITA",    sillabe: ["FE",   "RI",   "TA"]    },
{ parola: "FIDARE",    sillabe: ["FI",   "DA",   "RE"]    },
{ parola: "FILARE",    sillabe: ["FI",   "LA",   "RE"]    },
{ parola: "FILONE",    sillabe: ["FI",   "LO",   "NE"]    },
{ parola: "FINALE",    sillabe: ["FI",   "NA",   "LE"]    },
{ parola: "FORARE",    sillabe: ["FO",   "RA",   "RE"]    },
{ parola: "FUCILE",    sillabe: ["FU",   "CI",   "LE"]    },
{ parola: "FUMARE",    sillabe: ["FU",   "MA",   "RE"]    },
{ parola: "FUMATA",    sillabe: ["FU",   "MA",   "TA"]    },
{ parola: "GALERA",    sillabe: ["GA",   "LE",   "RA"]    },
{ parola: "GARIGA",    sillabe: ["GA",   "RI",   "GA"]    },
{ parola: "GELARE",    sillabe: ["GE",   "LA",   "RE"]    },
{ parola: "GELATO",    sillabe: ["GE",   "LA",   "TO"]    },
{ parola: "GENERI",    sillabe: ["GE",   "NE",   "RI"]    },
{ parola: "GENESI",    sillabe: ["GE",   "NE",   "SI"]    },
{ parola: "GENOVA",    sillabe: ["GE",   "NO",   "VA"]    },
{ parola: "GIRARE",    sillabe: ["GI",   "RA",   "RE"]    },
{ parola: "GIRONE",    sillabe: ["GI",   "RO",   "NE"]    },
{ parola: "GITANO",    sillabe: ["GI",   "TA",   "NO"]    },
{ parola: "GOMITO",    sillabe: ["GO",   "MI",   "TO"]    },
{ parola: "GUFARE",    sillabe: ["GU",   "FA",   "RE"]    },
{ parola: "IDOLO",    sillabe: ["I",   "DO",   "LO"]    },
{ parola: "IMOLA",    sillabe: ["I",   "MO",   "LA"]    },
{ parola: "IRATO",    sillabe: ["I",   "RA",   "TO"]    },
{ parola: "ISOLA",    sillabe: ["I",   "SO",   "LA"]    },
{ parola: "LEGAME",    sillabe: ["LE",   "GA",   "ME"]    },
{ parola: "LEGARE",    sillabe: ["LE",   "GA",   "RE"]    },
{ parola: "LEONE",    sillabe: ["LE",   "O",   "NE"]    },
{ parola: "LIMONE",    sillabe: ["LI",   "MO",   "NE"]    },
{ parola: "LIRICA",    sillabe: ["LI",   "RI",   "CA"]    },
{ parola: "LIVIDO",    sillabe: ["LI",   "VI",   "DO"]    },
{ parola: "LOCALI",    sillabe: ["LO",   "CA",   "LI"]    },
{ parola: "LOGICA",    sillabe: ["LO",   "GI",   "CA"]    },
{ parola: "LUMACA",    sillabe: ["LU",   "MA",   "CA"]    },
{ parola: "LUNARE",    sillabe: ["LU",   "NA",   "RE"]    },
{ parola: "MALATO",    sillabe: ["MA",   "LA",   "TO"]    },
{ parola: "MALORA",    sillabe: ["MA",   "LO",   "RA"]    },
{ parola: "MANICA",    sillabe: ["MA",   "NI",   "CA"]    },
{ parola: "MANINA",    sillabe: ["MA",   "NI",   "NA"]    },
{ parola: "MARITO",    sillabe: ["MA",   "RI",   "TO"]    },
{ parola: "MEDUSA",    sillabe: ["ME",   "DU",   "SA"]    },
{ parola: "MELONE",    sillabe: ["ME",   "LO",   "NE"]    },
{ parola: "MIRARE",    sillabe: ["MI",   "RA",   "RE"]    },
{ parola: "MIRATO",    sillabe: ["MI",   "RA",   "TO"]    },
{ parola: "MODENA",    sillabe: ["MO",   "DE",   "NA"]    },
{ parola: "MONETA",    sillabe: ["MO",   "NE",   "TA"]    },
{ parola: "MORENA",    sillabe: ["MO",   "RE",   "NA"]    },
{ parola: "MOTORE",    sillabe: ["MO",   "TO",   "RE"]    },
{ parola: "MULINO",    sillabe: ["MU",   "LI",   "NO"]    },
{ parola: "NATURA",    sillabe: ["NA",   "TU",   "RA"]    },
{ parola: "NAVATA",    sillabe: ["NA",   "VA",   "TA"]    },
{ parola: "NOCIVO",    sillabe: ["NO",   "CI",   "VO"]    },
{ parola: "NOMADE",    sillabe: ["NO",   "MA",   "DE"]    },
{ parola: "NUVOLA",    sillabe: ["NU",   "VO",   "LA"]    },
{ parola: "PAGARE",    sillabe: ["PA",   "GA",   "RE"]    },
{ parola: "PARATA",    sillabe: ["PA",   "RA",   "TA"]    },
{ parola: "PATATA",    sillabe: ["PA",   "TA",   "TA"]    },
{ parola: "PELAME",    sillabe: ["PE",   "LA",   "ME"]    },
{ parola: "PECORA",    sillabe: ["PE",   "CO",   "RA"]    },
{ parola: "PILOTA",    sillabe: ["PI",   "LO",   "TA"]    },
{ parola: "ABOLIRE",    sillabe: ["A",   "BO",   "LI",   "RE"]    },
{ parola: "ABOLITO",    sillabe: ["A",   "BO",   "LI",   "TO"]    },
{ parola: "ADIRATO",    sillabe: ["A",   "DI",   "RA",   "TO"]    },
{ parola: "ADUNATA",    sillabe: ["A",   "DU",   "NA",   "TA"]    },
{ parola: "AGITARE",    sillabe: ["A",   "GI",   "TA",   "RE"]    },
{ parola: "AGITATO",    sillabe: ["A",   "GI",   "TA",   "TO"]    },
{ parola: "AGONIA",    sillabe: ["A",   "GO",   "NI",   "A"]    },
{ parola: "AMABILE",    sillabe: ["A",   "MA",   "BI",   "LE"]    },
{ parola: "AMARENA",    sillabe: ["A",   "MA",   "RE",   "NA"]    },
{ parola: "ANOMALO",    sillabe: ["A",   "NO",   "MA",   "LO"]    },
{ parola: "APATICO",    sillabe: ["A",   "PA",   "TI",   "CO"]    },
{ parola: "AVIDITÀ",    sillabe: ["A",   "VI",   "DI",   "TÀ"]    },
{ parola: "BANALITÀ",    sillabe: ["BA",   "NA",   "LI",   "TÀ"]    },
{ parola: "BICOLORE",    sillabe: ["BI",   "CO",   "LO",   "RE"]    },
{ parola: "BIPOLARE",    sillabe: ["BI",   "PO",   "LA",   "RE"]    },
{ parola: "BOTANICA",    sillabe: ["BO",   "TA",   "NI",   "CA"]    },
{ parola: "BUFALONA",    sillabe: ["BU",   "FA",   "LO",   "NA"]    },
{ parola: "CALIMERO",    sillabe: ["CA",   "LI",   "ME",   "RO"]    },
{ parola: "CALORICO",    sillabe: ["CA",   "LO",   "RI",   "CO"]    },
{ parola: "CAMERINO",    sillabe: ["CA",   "ME",   "RI",   "NO"]    },
{ parola: "CANALONE",    sillabe: ["CA",   "NA",   "LO",   "NE"]    },
{ parola: "CANARINO",    sillabe: ["CA",   "NA",   "RI",   "NO"]    },
{ parola: "CAPITANA",    sillabe: ["CA",   "PI",   "TA",   "NA"]    },
{ parola: "CAPITANO",    sillabe: ["CA",   "PI",   "TA",   "NO"]    },
{ parola: "CAPONATA",    sillabe: ["CA",   "PO",   "NA",   "TA"]    },
{ parola: "CAPOVALE",    sillabe: ["CA",   "PO",   "VA",   "LE"]    },
{ parola: "CARITATE",    sillabe: ["CA",   "RI",   "TA",   "TE"]    },
{ parola: "CELERITÀ",    sillabe: ["CE",   "LE",   "RI",   "TÀ"]    },
{ parola: "CENERINO",    sillabe: ["CE",   "NE",   "RI",   "NO"]    },
{ parola: "CITOFONO",    sillabe: ["CI",   "TO",   "FO",   "NO"]    },
{ parola: "COLORARE",    sillabe: ["CO",   "LO",   "RA",   "RE"]    },
{ parola: "COLORATO",    sillabe: ["CO",   "LO",   "RA",   "TO"]    },
{ parola: "COMITATO",    sillabe: ["CO",   "MI",   "TA",   "TO"]    },
{ parola: "COMODITÀ",    sillabe: ["CO",   "MO",   "DI",   "TÀ"]    },
{ parola: "COMUNALE",    sillabe: ["CO",   "MU",   "NA",   "LE"]    },
{ parola: "COMICITÀ",    sillabe: ["CO",   "MI",   "CI",   "TÀ"]    },
{ parola: "CUPOLINO",    sillabe: ["CU",   "PO",   "LI",   "NO"]    },
{ parola: "DECADUTO",    sillabe: ["DE",   "CA",   "DU",   "TO"]    },
{ parola: "DECIDERE",    sillabe: ["DE",   "CI",   "DE",   "RE"]    },
{ parola: "DELICATO",    sillabe: ["DE",   "LI",   "CA",   "TO"]    },
{ parola: "DELIRARE",    sillabe: ["DE",   "LI",   "RA",   "RE"]    },
{ parola: "DENOTARE",    sillabe: ["DE",   "NO",   "TA",   "RE"]    },
{ parola: "DEPILATO",    sillabe: ["DE",   "PI",   "LA",   "TO"]    },
{ parola: "DERIVARE",    sillabe: ["DE",   "RI",   "VA",   "RE"]    },
{ parola: "DERIVATO",    sillabe: ["DE",   "RI",   "VA",   "TO"]    },
{ parola: "DESOLATI",    sillabe: ["DE",   "SO",   "LA",   "TI"]    },
{ parola: "DESOLATO",    sillabe: ["DE",   "SO",   "LA",   "TO"]    },
{ parola: "DINAMICA",    sillabe: ["DI",   "NA",   "MI",   "CA"]    },
{ parola: "DINAMICO",    sillabe: ["DI",   "NA",   "MI",   "CO"]    },
{ parola: "DIPANARE",    sillabe: ["DI",   "PA",   "NA",   "RE"]    },
{ parola: "DIVENIRE",    sillabe: ["DI",   "VE",   "NI",   "RE"]    },
{ parola: "DOCILITÀ",    sillabe: ["DO",   "CI",   "LI",   "TÀ"]    },
{ parola: "DOLOROSO",    sillabe: ["DO",   "LO",   "RO",   "SO"]    },
{ parola: "DOMENICA",    sillabe: ["DO",   "ME",   "NI",   "CA"]    },
{ parola: "DOMINARE",    sillabe: ["DO",   "MI",   "NA",   "RE"]    },
{ parola: "DOMINATO",    sillabe: ["DO",   "MI",   "NA",   "TO"]    },
{ parola: "DONATORE",    sillabe: ["DO",   "NA",   "TO",   "RE"]    },
{ parola: "DORATURA",    sillabe: ["DO",   "RA",   "TU",   "RA"]    },
{ parola: "DOVEROSO",    sillabe: ["DO",   "VE",   "RO",   "SO"]    },
{ parola: "EMANARE",    sillabe: ["E",   "MA",   "NA",   "RE"]    },
{ parola: "EMANATO",    sillabe: ["E",   "MA",   "NA",   "TO"]    },
{ parola: "EPURATO",    sillabe: ["E",   "PU",   "RA",   "TO"]    },
{ parola: "EREDITÀ",    sillabe: ["E",   "RE",   "DI",   "TÀ"]    },
{ parola: "EROGARE",    sillabe: ["E",   "RO",   "GA",   "RE"]    },
{ parola: "EROGATO",    sillabe: ["E",   "RO",   "GA",   "TO"]    },
{ parola: "ESOTICO",    sillabe: ["E",   "SO",   "TI",   "CO"]    },
{ parola: "EVITATO",    sillabe: ["E",   "VI",   "TA",   "TO"]    },
{ parola: "FATICARE",    sillabe: ["FA",   "TI",   "CA",   "RE"]    },
{ parola: "FATICATO",    sillabe: ["FA",   "TI",   "CA",   "TO"]    },
{ parola: "FAVOLOSA",    sillabe: ["FA",   "VO",   "LO",   "SA"]    },
{ parola: "FAVOLOSO",    sillabe: ["FA",   "VO",   "LO",   "SO"]    },
{ parola: "FELICITÀ",    sillabe: ["FE",   "LI",   "CI",   "TÀ"]    },
{ parola: "FILOSOFO",    sillabe: ["FI",   "LO",   "SO",   "FO"]    },
{ parola: "FINITURA",    sillabe: ["FI",   "NI",   "TU",   "RA"]    },
{ parola: "GENERALE",    sillabe: ["GE",   "NE",   "RA",   "LE"]    },
{ parola: "GENERATO",    sillabe: ["GE",   "NE",   "RA",   "TO"]    },
{ parola: "GENITORI",    sillabe: ["GE",   "NI",   "TO",   "RI"]    },
{ parola: "GUFATORE",    sillabe: ["GU",   "FA",   "TO",   "RE"]    },
];
